# Generated by Django 5.2.14 on 2026-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs_index', '0001_initial'),
        ('expenses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationrecord',
            name='related_expenses',
            field=models.ManyToManyField(blank=True, related_name='documentation_records', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='documentationrecord',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='documentation_records', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='documentationrecord',
            index=models.Index(fields=['status'], name='docs_index__status_90607d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationrecord',
            index=models.Index(fields=['doc_type'], name='docs_index__doc_typ_f3bf58_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationrecord',
            index=models.Index(fields=['environment'], name='docs_index__environ_1f67f7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationrecord',
            index=models.Index(fields=['sensitivity'], name='docs_index__sensiti_7cda62_idx'),
        ),
        migrations.AddIndex(
            model_name='documentationrecord',
            index=models.Index(fields=['last_reviewed'], name='docs_index__last_re_1dd0e1_idx'),
        ),
    ]
