# Generated by Django 5.2.14 on 2026-05-16 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category', models.CharField(choices=[('wordpress_security', 'WordPress security'), ('cloudflare', 'Cloudflare'), ('dns_email_security', 'DNS / email security'), ('homelab', 'Homelab'), ('vps', 'VPS'), ('tailscale', 'Tailscale'), ('adguard', 'AdGuard'), ('networking', 'UniFi / networking'), ('tls_certificates', 'TLS / certificates'), ('automation', 'Automation / scripts'), ('cybersecurity_labs', 'Cybersecurity labs'), ('other', 'Other')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('technologies_used', models.CharField(blank=True, help_text='Comma-separated list of technologies.', max_length=300)),
                ('repository_url', models.URLField(blank=True)),
                ('public_url', models.URLField(blank=True)),
                ('deployment_notes', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['category'], name='projects_pr_categor_220446_idx')],
            },
        ),
    ]
