// Package adguardapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package adguardapi

// Defines values for DNSConfigBlockingMode.
const (
	DNSConfigBlockingModeCustomIp DNSConfigBlockingMode = "custom_ip"
	DNSConfigBlockingModeDefault  DNSConfigBlockingMode = "default"
	DNSConfigBlockingModeNullIp   DNSConfigBlockingMode = "null_ip"
	DNSConfigBlockingModeNxdomain DNSConfigBlockingMode = "nxdomain"
	DNSConfigBlockingModeRefused  DNSConfigBlockingMode = "refused"
)

// Valid indicates whether the value is a known member of the DNSConfigBlockingMode enum.
func (e DNSConfigBlockingMode) Valid() bool {
	switch e {
	case DNSConfigBlockingModeCustomIp:
		return true
	case DNSConfigBlockingModeDefault:
		return true
	case DNSConfigBlockingModeNullIp:
		return true
	case DNSConfigBlockingModeNxdomain:
		return true
	case DNSConfigBlockingModeRefused:
		return true
	default:
		return false
	}
}

// Defines values for DNSConfigUpstreamMode.
const (
	DNSConfigUpstreamModeEmpty       DNSConfigUpstreamMode = ""
	DNSConfigUpstreamModeFastestAddr DNSConfigUpstreamMode = "fastest_addr"
	DNSConfigUpstreamModeLoadBalance DNSConfigUpstreamMode = "load_balance"
	DNSConfigUpstreamModeParallel    DNSConfigUpstreamMode = "parallel"
)

// Valid indicates whether the value is a known member of the DNSConfigUpstreamMode enum.
func (e DNSConfigUpstreamMode) Valid() bool {
	switch e {
	case DNSConfigUpstreamModeEmpty:
		return true
	case DNSConfigUpstreamModeFastestAddr:
		return true
	case DNSConfigUpstreamModeLoadBalance:
		return true
	case DNSConfigUpstreamModeParallel:
		return true
	default:
		return false
	}
}

// Defines values for FilteringReason.
const (
	FilteredBlackList      FilteringReason = "FilteredBlackList"
	FilteredBlockedService FilteringReason = "FilteredBlockedService"
	FilteredInvalid        FilteringReason = "FilteredInvalid"
	FilteredParental       FilteringReason = "FilteredParental"
	FilteredSafeBrowsing   FilteringReason = "FilteredSafeBrowsing"
	FilteredSafeSearch     FilteringReason = "FilteredSafeSearch"
	NotFilteredError       FilteringReason = "NotFilteredError"
	NotFilteredNotFound    FilteringReason = "NotFilteredNotFound"
	NotFilteredWhiteList   FilteringReason = "NotFilteredWhiteList"
	Rewrite                FilteringReason = "Rewrite"
	RewriteEtcHosts        FilteringReason = "RewriteEtcHosts"
	RewriteRule            FilteringReason = "RewriteRule"
)

// Valid indicates whether the value is a known member of the FilteringReason enum.
func (e FilteringReason) Valid() bool {
	switch e {
	case FilteredBlackList:
		return true
	case FilteredBlockedService:
		return true
	case FilteredInvalid:
		return true
	case FilteredParental:
		return true
	case FilteredSafeBrowsing:
		return true
	case FilteredSafeSearch:
		return true
	case NotFilteredError:
		return true
	case NotFilteredNotFound:
		return true
	case NotFilteredWhiteList:
		return true
	case Rewrite:
		return true
	case RewriteEtcHosts:
		return true
	case RewriteRule:
		return true
	default:
		return false
	}
}

// Defines values for Lang.
const (
	Ar   Lang = "ar"
	Be   Lang = "be"
	Bg   Lang = "bg"
	Cs   Lang = "cs"
	Da   Lang = "da"
	De   Lang = "de"
	En   Lang = "en"
	Es   Lang = "es"
	Fa   Lang = "fa"
	Fi   Lang = "fi"
	Fr   Lang = "fr"
	Hr   Lang = "hr"
	Hu   Lang = "hu"
	Id   Lang = "id"
	It   Lang = "it"
	Ja   Lang = "ja"
	Ko   Lang = "ko"
	Nl   Lang = "nl"
	No   Lang = "no"
	Pl   Lang = "pl"
	PtBr Lang = "pt-br"
	PtPt Lang = "pt-pt"
	Ro   Lang = "ro"
	Ru   Lang = "ru"
	SiLk Lang = "si-lk"
	Sk   Lang = "sk"
	Sl   Lang = "sl"
	SrCs Lang = "sr-cs"
	Sv   Lang = "sv"
	Th   Lang = "th"
	Tr   Lang = "tr"
	Uk   Lang = "uk"
	Vi   Lang = "vi"
	ZhCn Lang = "zh-cn"
	ZhHk Lang = "zh-hk"
	ZhTw Lang = "zh-tw"
)

// Valid indicates whether the value is a known member of the Lang enum.
func (e Lang) Valid() bool {
	switch e {
	case Ar:
		return true
	case Be:
		return true
	case Bg:
		return true
	case Cs:
		return true
	case Da:
		return true
	case De:
		return true
	case En:
		return true
	case Es:
		return true
	case Fa:
		return true
	case Fi:
		return true
	case Fr:
		return true
	case Hr:
		return true
	case Hu:
		return true
	case Id:
		return true
	case It:
		return true
	case Ja:
		return true
	case Ko:
		return true
	case Nl:
		return true
	case No:
		return true
	case Pl:
		return true
	case PtBr:
		return true
	case PtPt:
		return true
	case Ro:
		return true
	case Ru:
		return true
	case SiLk:
		return true
	case Sk:
		return true
	case Sl:
		return true
	case SrCs:
		return true
	case Sv:
		return true
	case Th:
		return true
	case Tr:
		return true
	case Uk:
		return true
	case Vi:
		return true
	case ZhCn:
		return true
	case ZhHk:
		return true
	case ZhTw:
		return true
	default:
		return false
	}
}

// Defines values for QueryLogItemClientProto.
const (
	QueryLogItemClientProtoDnscrypt QueryLogItemClientProto = "dnscrypt"
	QueryLogItemClientProtoDoh      QueryLogItemClientProto = "doh"
	QueryLogItemClientProtoDoq      QueryLogItemClientProto = "doq"
	QueryLogItemClientProtoDot      QueryLogItemClientProto = "dot"
	QueryLogItemClientProtoEmpty    QueryLogItemClientProto = ""
)

// Valid indicates whether the value is a known member of the QueryLogItemClientProto enum.
func (e QueryLogItemClientProto) Valid() bool {
	switch e {
	case QueryLogItemClientProtoDnscrypt:
		return true
	case QueryLogItemClientProtoDoh:
		return true
	case QueryLogItemClientProtoDoq:
		return true
	case QueryLogItemClientProtoDot:
		return true
	case QueryLogItemClientProtoEmpty:
		return true
	default:
		return false
	}
}

// Defines values for DnsInfo200JSONResponseBodyBlockingMode.
const (
	DnsInfo200JSONResponseBodyBlockingModeCustomIp DnsInfo200JSONResponseBodyBlockingMode = "custom_ip"
	DnsInfo200JSONResponseBodyBlockingModeDefault  DnsInfo200JSONResponseBodyBlockingMode = "default"
	DnsInfo200JSONResponseBodyBlockingModeNullIp   DnsInfo200JSONResponseBodyBlockingMode = "null_ip"
	DnsInfo200JSONResponseBodyBlockingModeNxdomain DnsInfo200JSONResponseBodyBlockingMode = "nxdomain"
	DnsInfo200JSONResponseBodyBlockingModeRefused  DnsInfo200JSONResponseBodyBlockingMode = "refused"
)

// Valid indicates whether the value is a known member of the DnsInfo200JSONResponseBodyBlockingMode enum.
func (e DnsInfo200JSONResponseBodyBlockingMode) Valid() bool {
	switch e {
	case DnsInfo200JSONResponseBodyBlockingModeCustomIp:
		return true
	case DnsInfo200JSONResponseBodyBlockingModeDefault:
		return true
	case DnsInfo200JSONResponseBodyBlockingModeNullIp:
		return true
	case DnsInfo200JSONResponseBodyBlockingModeNxdomain:
		return true
	case DnsInfo200JSONResponseBodyBlockingModeRefused:
		return true
	default:
		return false
	}
}

// Defines values for DnsInfo200JSONResponseBodyUpstreamMode.
const (
	DnsInfo200JSONResponseBodyUpstreamModeEmpty       DnsInfo200JSONResponseBodyUpstreamMode = ""
	DnsInfo200JSONResponseBodyUpstreamModeFastestAddr DnsInfo200JSONResponseBodyUpstreamMode = "fastest_addr"
	DnsInfo200JSONResponseBodyUpstreamModeLoadBalance DnsInfo200JSONResponseBodyUpstreamMode = "load_balance"
	DnsInfo200JSONResponseBodyUpstreamModeParallel    DnsInfo200JSONResponseBodyUpstreamMode = "parallel"
)

// Valid indicates whether the value is a known member of the DnsInfo200JSONResponseBodyUpstreamMode enum.
func (e DnsInfo200JSONResponseBodyUpstreamMode) Valid() bool {
	switch e {
	case DnsInfo200JSONResponseBodyUpstreamModeEmpty:
		return true
	case DnsInfo200JSONResponseBodyUpstreamModeFastestAddr:
		return true
	case DnsInfo200JSONResponseBodyUpstreamModeLoadBalance:
		return true
	case DnsInfo200JSONResponseBodyUpstreamModeParallel:
		return true
	default:
		return false
	}
}

// Defines values for QueryLogParamsResponseStatus.
const (
	All                 QueryLogParamsResponseStatus = "all"
	Blocked             QueryLogParamsResponseStatus = "blocked"
	BlockedParental     QueryLogParamsResponseStatus = "blocked_parental"
	BlockedSafebrowsing QueryLogParamsResponseStatus = "blocked_safebrowsing"
	Filtered            QueryLogParamsResponseStatus = "filtered"
	Processed           QueryLogParamsResponseStatus = "processed"
	Rewritten           QueryLogParamsResponseStatus = "rewritten"
	SafeSearch          QueryLogParamsResponseStatus = "safe_search"
	Whitelisted         QueryLogParamsResponseStatus = "whitelisted"
)

// Valid indicates whether the value is a known member of the QueryLogParamsResponseStatus enum.
func (e QueryLogParamsResponseStatus) Valid() bool {
	switch e {
	case All:
		return true
	case Blocked:
		return true
	case BlockedParental:
		return true
	case BlockedSafebrowsing:
		return true
	case Filtered:
		return true
	case Processed:
		return true
	case Rewritten:
		return true
	case SafeSearch:
		return true
	case Whitelisted:
		return true
	default:
		return false
	}
}

// Client Client information.
type Client struct {
	BlockedServices *[]string `json:"blocked_services,omitempty"`

	// BlockedServicesSchedule Sets periods of inactivity for filtering blocked services.  The schedule contains 7 days (Sunday to Saturday) and a time zone.
	BlockedServicesSchedule *Schedule `json:"blocked_services_schedule,omitempty"`
	FilteringEnabled        *bool     `json:"filtering_enabled,omitempty"`

	// Ids IP, CIDR, MAC, or ClientID.
	Ids *[]string `json:"ids,omitempty"`

	// IgnoreQuerylog NOTE: If `ignore_querylog` is not set in HTTP API `GET /clients/add`
	// request then default value (false) will be used.
	//
	// If `ignore_querylog` is not set in HTTP API `GET /clients/update`
	// request then the existing value will not be changed.
	//
	// This behaviour can be changed in the future versions.
	IgnoreQuerylog *bool `json:"ignore_querylog,omitempty"`

	// IgnoreStatistics NOTE: If `ignore_statistics` is not set in HTTP API `GET
	// /clients/add` request then default value (false) will be used.
	//
	// If `ignore_statistics` is not set in HTTP API `GET /clients/update`
	// request then the existing value will not be changed.
	//
	// This behaviour can be changed in the future versions.
	IgnoreStatistics *bool `json:"ignore_statistics,omitempty"`

	// Name Name
	Name            *string `json:"name,omitempty"`
	ParentalEnabled *bool   `json:"parental_enabled,omitempty"`

	// SafeSearch Safe search settings.
	SafeSearch          *SafeSearchConfig `json:"safe_search,omitempty"`
	SafebrowsingEnabled *bool             `json:"safebrowsing_enabled,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SafesearchEnabled *bool     `json:"safesearch_enabled,omitempty"`
	Tags              *[]string `json:"tags,omitempty"`
	Upstreams         *[]string `json:"upstreams,omitempty"`

	// UpstreamsCacheEnabled NOTE: If `upstreams_cache_enabled` is not set in HTTP API
	// `GET /clients/add` request then default value (false) will be used.
	//
	// If `upstreams_cache_enabled` is not set in HTTP API
	// `GET /clients/update` request then the existing value will not be
	// changed.
	//
	// This behaviour can be changed in the future versions.
	UpstreamsCacheEnabled *bool `json:"upstreams_cache_enabled,omitempty"`

	// UpstreamsCacheSize NOTE: If `upstreams_cache_enabled` is not set in HTTP API
	// `GET /clients/update` request then the existing value will not be
	// changed.
	//
	// This behaviour can be changed in the future versions.
	UpstreamsCacheSize       *int  `json:"upstreams_cache_size,omitempty"`
	UseGlobalBlockedServices *bool `json:"use_global_blocked_services,omitempty"`
	UseGlobalSettings        *bool `json:"use_global_settings,omitempty"`
}

// ClientAuto Auto-Client information
type ClientAuto struct {
	// Ip IP address
	Ip *string `json:"ip,omitempty"`

	// Name Name
	Name *string `json:"name,omitempty"`

	// Source The source of this information
	Source    *string    `json:"source,omitempty"`
	WhoisInfo *WhoisInfo `json:"whois_info,omitempty"`
}

// Clients defines model for Clients.
type Clients struct {
	// AutoClients Auto-Clients array
	AutoClients *ClientsAutoArray `json:"auto_clients,omitempty"`

	// Clients Clients array
	Clients       *ClientsArray `json:"clients,omitempty"`
	SupportedTags *[]string     `json:"supported_tags,omitempty"`
}

// ClientsArray Clients array
type ClientsArray = []Client

// ClientsAutoArray Auto-Clients array
type ClientsAutoArray = []ClientAuto

// DNSConfig DNS server configuration
type DNSConfig struct {
	// BlockedResponseTtl TTL for blocked responses.
	BlockedResponseTtl *int                   `json:"blocked_response_ttl,omitempty"`
	BlockingIpv4       *string                `json:"blocking_ipv4,omitempty"`
	BlockingIpv6       *string                `json:"blocking_ipv6,omitempty"`
	BlockingMode       *DNSConfigBlockingMode `json:"blocking_mode,omitempty"`

	// BootstrapDns Bootstrap servers, port is optional after colon.  Empty value will reset it to default values.  Comments are allowed, a comment line starts with a `#` symbol.
	BootstrapDns *[]string `json:"bootstrap_dns,omitempty"`

	// CacheEnabled Enables or disables the DNS response cache.
	//
	// If `cache_enabled` is `true`, the companion field `cache_size` must
	// be present and greater than 0, or the `dns.cache_size` setting in
	// the configuration file must already be greater than 0.
	CacheEnabled    *bool   `json:"cache_enabled,omitempty"`
	CacheOptimistic *bool   `json:"cache_optimistic,omitempty"`
	CacheSize       *int    `json:"cache_size,omitempty"`
	CacheTtlMax     *int    `json:"cache_ttl_max,omitempty"`
	CacheTtlMin     *int    `json:"cache_ttl_min,omitempty"`
	DisableIpv6     *bool   `json:"disable_ipv6,omitempty"`
	DnssecEnabled   *bool   `json:"dnssec_enabled,omitempty"`
	EdnsCsCustomIp  *string `json:"edns_cs_custom_ip,omitempty"`
	EdnsCsEnabled   *bool   `json:"edns_cs_enabled,omitempty"`
	EdnsCsUseCustom *bool   `json:"edns_cs_use_custom,omitempty"`

	// FallbackDns List of fallback DNS servers used when upstream DNS servers are not responding.  Empty value will clear the list.  Comments are allowed, a comment line starts with a `#` symbol.
	FallbackDns *[]string `json:"fallback_dns,omitempty"`

	// LocalPtrUpstreams Upstream servers, port is optional after colon.  Empty value will reset it to default values.  Comments are allowed, a comment line starts with a `#` symbol.
	LocalPtrUpstreams *[]string `json:"local_ptr_upstreams,omitempty"`

	// ProtectionDisabledUntil Protection is pause until this time.  Nullable.
	ProtectionDisabledUntil *string `json:"protection_disabled_until,omitempty"`
	ProtectionEnabled       *bool   `json:"protection_enabled,omitempty"`
	Ratelimit               *int    `json:"ratelimit,omitempty"`

	// RatelimitSubnetLenIpv4 Length of the subnet mask for IPv4 addresses.
	RatelimitSubnetLenIpv4 *int `json:"ratelimit_subnet_len_ipv4,omitempty"`

	// RatelimitSubnetLenIpv6 Length of the subnet mask for IPv6 addresses.
	RatelimitSubnetLenIpv6 *int `json:"ratelimit_subnet_len_ipv6,omitempty"`

	// RatelimitWhitelist List of IP addresses excluded from rate limiting.
	RatelimitWhitelist *[]string `json:"ratelimit_whitelist,omitempty"`
	ResolveClients     *bool     `json:"resolve_clients,omitempty"`

	// UpstreamDns Upstream servers, port is optional after colon.  Empty value will reset it to default values.  Comments are allowed, a comment line starts with a `#` symbol.
	UpstreamDns     *[]string `json:"upstream_dns,omitempty"`
	UpstreamDnsFile *string   `json:"upstream_dns_file,omitempty"`

	// UpstreamMode Upstream modes enumeration. The empty string value is deprecated; use `load_balance` instead.
	UpstreamMode *DNSConfigUpstreamMode `json:"upstream_mode,omitempty"`

	// UpstreamTimeout The number of seconds to wait for a response from the upstream server
	UpstreamTimeout        *int  `json:"upstream_timeout,omitempty"`
	UsePrivatePtrResolvers *bool `json:"use_private_ptr_resolvers,omitempty"`
}

// DNSConfigBlockingMode defines model for DNSConfig.BlockingMode.
type DNSConfigBlockingMode string

// DNSConfigUpstreamMode Upstream modes enumeration. The empty string value is deprecated; use `load_balance` instead.
type DNSConfigUpstreamMode string

// DayRange The single interval within a day.  It begins at the `start` and ends before the `end`.
type DayRange struct {
	// End The number of milliseconds elapsed from the start of a day.  It is expected to be rounded to minutes.  The maximum value is `86400000` (24 hours).
	End *float32 `json:"end,omitempty"`

	// Start The number of milliseconds elapsed from the start of a day.  It must be less than `end` and is expected to be rounded to minutes. So the maximum value is `86340000` (23 hours and 59 minutes).
	Start *float32 `json:"start,omitempty"`
}

// DnsAnswer DNS answer section
type DnsAnswer struct {
	Ttl   *uint32 `json:"ttl,omitempty"`
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
}

// DnsQuestion DNS question section
type DnsQuestion struct {
	Class       *string `json:"class,omitempty"`
	Name        *string `json:"name,omitempty"`
	Type        *string `json:"type,omitempty"`
	UnicodeName *string `json:"unicode_name,omitempty"`
}

// Filter Filter subscription info
type Filter struct {
	Enabled     *bool   `json:"enabled,omitempty"`
	Id          *int64  `json:"id,omitempty"`
	LastUpdated *string `json:"last_updated,omitempty"`
	Name        *string `json:"name,omitempty"`
	RulesCount  *int64  `json:"rules_count,omitempty"`
	Url         *string `json:"url,omitempty"`
}

// FilterStatus Filtering settings
type FilterStatus struct {
	Enabled          *bool     `json:"enabled,omitempty"`
	Filters          *[]Filter `json:"filters,omitempty"`
	Interval         *int      `json:"interval,omitempty"`
	UserRules        *[]string `json:"user_rules,omitempty"`
	WhitelistFilters *[]Filter `json:"whitelist_filters,omitempty"`
}

// FilteringReason Request filtering status.
type FilteringReason string

// GetQueryLogConfigResponse Query log configuration
type GetQueryLogConfigResponse struct {
	// AnonymizeClientIp Anonymize clients' IP addresses
	AnonymizeClientIp *bool `json:"anonymize_client_ip,omitempty"`

	// Enabled Is query log enabled
	Enabled *bool `json:"enabled,omitempty"`

	// Ignored List of host names, which should not be written to log
	Ignored *[]string `json:"ignored,omitempty"`

	// IgnoredEnabled If true, the host names in the `ignored` array are excluded from the query log.
	IgnoredEnabled *bool `json:"ignored_enabled,omitempty"`

	// Interval Time period for query log rotation in milliseconds.
	Interval *float64 `json:"interval,omitempty"`
}

// Lang Language code.
type Lang string

// QueryLog Query log
type QueryLog struct {
	Data   *[]QueryLogItem `json:"data,omitempty"`
	Oldest *string         `json:"oldest,omitempty"`
}

// QueryLogItem Query log item
type QueryLogItem struct {
	Answer *[]DnsAnswer `json:"answer,omitempty"`

	// AnswerDnssec If true, the response had the Authenticated Data (AD) flag set.
	AnswerDnssec *bool `json:"answer_dnssec,omitempty"`

	// Cached Defines if the response has been served from cache.
	Cached *bool `json:"cached,omitempty"`

	// Client The client's IP address.
	Client *string `json:"client,omitempty"`

	// ClientId The ClientID, if provided in DoH, DoQ, or DoT.
	ClientId *string `json:"client_id,omitempty"`

	// ClientInfo Client information for a query log item.
	ClientInfo  *QueryLogItemClient      `json:"client_info,omitempty"`
	ClientProto *QueryLogItemClientProto `json:"client_proto,omitempty"`

	// Ecs The IP network defined by an EDNS Client-Subnet option in the request message if any.
	Ecs       *string `json:"ecs,omitempty"`
	ElapsedMs *string `json:"elapsedMs,omitempty"`

	// FilterId In case if there's a rule applied to this DNS request, this is ID of the filter list that the rule belongs to.
	// Deprecated: use `rules[*].filter_list_id` instead.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	FilterId *int `json:"filterId,omitempty"`

	// OriginalAnswer Answer from upstream server (optional)
	OriginalAnswer *[]DnsAnswer `json:"original_answer,omitempty"`

	// Question DNS question section
	Question *DnsQuestion `json:"question,omitempty"`

	// Reason Request filtering status.
	Reason *FilteringReason `json:"reason,omitempty"`

	// Rule Filtering rule applied to the request (if any).
	// Deprecated: use `rules[*].text` instead.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Rule *string `json:"rule,omitempty"`

	// Rules Applied rules.
	Rules *[]ResultRule `json:"rules,omitempty"`

	// ServiceName Set if reason=FilteredBlockedService
	ServiceName *string `json:"service_name,omitempty"`

	// Status DNS response status
	Status *string `json:"status,omitempty"`

	// Time DNS request processing start time
	Time *string `json:"time,omitempty"`

	// Upstream Upstream URL starting with tcp://, tls://, https://, or with an IP address.
	Upstream *string `json:"upstream,omitempty"`
}

// QueryLogItemClientProto defines model for QueryLogItem.ClientProto.
type QueryLogItemClientProto string

// QueryLogItemClient Client information for a query log item.
type QueryLogItemClient struct {
	// Disallowed Whether the client's IP is blocked or not.
	Disallowed *bool `json:"disallowed,omitempty"`

	// DisallowedRule The rule due to which the client is allowed or blocked.
	DisallowedRule *string `json:"disallowed_rule,omitempty"`

	// Name Persistent client's name or runtime client's hostname.  May be empty.
	Name *string `json:"name,omitempty"`

	// Whois Client WHOIS information, if any.
	Whois *QueryLogItemClientWhois `json:"whois,omitempty"`
}

// QueryLogItemClientWhois Client WHOIS information, if any.
type QueryLogItemClientWhois struct {
	// City City, if any.
	City *string `json:"city,omitempty"`

	// Country Country, if any.
	Country *string `json:"country,omitempty"`

	// Orgname Organization name, if any.
	Orgname *string `json:"orgname,omitempty"`
}

// ResultRule Applied rule.
type ResultRule struct {
	// FilterListId In case if there's a rule applied to this DNS request, this is ID of the filter list that the rule belongs to.
	FilterListId *int64 `json:"filter_list_id,omitempty"`

	// Text The text of the filtering rule applied to the request (if any).
	Text *string `json:"text,omitempty"`
}

// RewriteEntry Rewrite rule
type RewriteEntry struct {
	// Answer value of A, AAAA or CNAME DNS record
	Answer *string `json:"answer,omitempty"`

	// Domain Domain name
	Domain *string `json:"domain,omitempty"`

	// Enabled Optional. If omitted on add, defaults to `true`. On update, omitted preserves previous value.
	Enabled *bool `json:"enabled,omitempty"`
}

// RewriteList Rewrite rules array
type RewriteList = []RewriteEntry

// RewriteSettings DNS rewrite settings
type RewriteSettings struct {
	// Enabled indicates whether rewrites are applied
	Enabled *bool `json:"enabled,omitempty"`
}

// RewriteUpdate Rewrite rule update object
type RewriteUpdate struct {
	// Target Rewrite rule
	Target *RewriteEntry `json:"target,omitempty"`

	// Update Rewrite rule
	Update *RewriteEntry `json:"update,omitempty"`
}

// SafeSearchConfig Safe search settings.
type SafeSearchConfig struct {
	Bing       *bool `json:"bing,omitempty"`
	Duckduckgo *bool `json:"duckduckgo,omitempty"`
	Ecosia     *bool `json:"ecosia,omitempty"`
	Enabled    *bool `json:"enabled,omitempty"`
	Google     *bool `json:"google,omitempty"`
	Pixabay    *bool `json:"pixabay,omitempty"`
	Yandex     *bool `json:"yandex,omitempty"`
	Youtube    *bool `json:"youtube,omitempty"`
}

// Schedule Sets periods of inactivity for filtering blocked services.  The schedule contains 7 days (Sunday to Saturday) and a time zone.
type Schedule struct {
	// Fri The single interval within a day.  It begins at the `start` and ends before the `end`.
	Fri *DayRange `json:"fri,omitempty"`

	// Mon The single interval within a day.  It begins at the `start` and ends before the `end`.
	Mon *DayRange `json:"mon,omitempty"`

	// Sat The single interval within a day.  It begins at the `start` and ends before the `end`.
	Sat *DayRange `json:"sat,omitempty"`

	// Sun The single interval within a day.  It begins at the `start` and ends before the `end`.
	Sun *DayRange `json:"sun,omitempty"`

	// Thu The single interval within a day.  It begins at the `start` and ends before the `end`.
	Thu *DayRange `json:"thu,omitempty"`

	// TimeZone Time zone name according to IANA time zone database.  For example `Europe/Brussels`.  `Local` represents the system's local time zone.
	TimeZone *string `json:"time_zone,omitempty"`

	// Tue The single interval within a day.  It begins at the `start` and ends before the `end`.
	Tue *DayRange `json:"tue,omitempty"`

	// Wed The single interval within a day.  It begins at the `start` and ends before the `end`.
	Wed *DayRange `json:"wed,omitempty"`
}

// ServerStatus AdGuard Home server status and configuration
type ServerStatus struct {
	DhcpAvailable *bool     `json:"dhcp_available,omitempty"`
	DnsAddresses  *[]string `json:"dns_addresses,omitempty"`
	DnsPort       *uint16   `json:"dns_port,omitempty"`
	HttpPort      *uint16   `json:"http_port,omitempty"`

	// Language Language code.
	Language                   *Lang  `json:"language,omitempty"`
	ProtectionDisabledDuration *int64 `json:"protection_disabled_duration,omitempty"`
	ProtectionEnabled          *bool  `json:"protection_enabled,omitempty"`
	Running                    *bool  `json:"running,omitempty"`

	// StartTime Start time of the web API server (Unix time in milliseconds).
	StartTime *float64 `json:"start_time,omitempty"`
	Version   *string  `json:"version,omitempty"`
}

// WhoisInfo defines model for WhoisInfo.
type WhoisInfo map[string]string

// DnsInfo200JSONResponseBodyBlockingMode defines parameters for DnsInfo.
type DnsInfo200JSONResponseBodyBlockingMode string

// DnsInfo200JSONResponseBodyUpstreamMode defines parameters for DnsInfo.
type DnsInfo200JSONResponseBodyUpstreamMode string

// QueryLogParams defines parameters for QueryLog.
type QueryLogParams struct {
	// OlderThan Filter by older than
	OlderThan *string `form:"older_than,omitempty" json:"older_than,omitempty"`

	// Offset Specify the ranking number of the first item on the page.  Even though it is possible to use "offset" and "older_than", we recommend choosing one of them and sticking to it.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit the number of records to be returned
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Search Filter by domain name or client IP
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// ResponseStatus Deprecated: Use 'reason' parameter instead Filter by response status
	// NOTE: This parameter cannot be used with 'reason' parameter.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	ResponseStatus *QueryLogParamsResponseStatus `form:"response_status,omitempty" json:"response_status,omitempty"`

	// Reason Filter by response filtering reason.  Multiple reasons can be provided.
	// NOTE: This parameter cannot be used with 'response_status' parameter.
	Reason *[]FilteringReason `form:"reason,omitempty" json:"reason,omitempty"`
}

// QueryLogParamsResponseStatus defines parameters for QueryLog.
type QueryLogParamsResponseStatus string

// RewriteAddJSONRequestBody defines body for RewriteAdd for application/json ContentType.
type RewriteAddJSONRequestBody = RewriteEntry

// RewriteDeleteJSONRequestBody defines body for RewriteDelete for application/json ContentType.
type RewriteDeleteJSONRequestBody = RewriteEntry

// RewriteUpdateJSONRequestBody defines body for RewriteUpdate for application/json ContentType.
type RewriteUpdateJSONRequestBody = RewriteUpdate
