# Generated by Django 6.1 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(max_length=255)),
                ("actor_sha256", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=128)),
                ("request_sha256", models.CharField(max_length=64)),
                ("response", models.JSONField(null=True)),
                ("status_code", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("actor_sha256", "key"),
                name="unique_api_idempotency_key_per_actor",
            ),
        ),
    ]
