# Generated by Django 6.1 on 2026-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agent_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('uploaded', 'Uploaded'), ('exported', 'Exported'), ('imported', 'Imported'), ('failed', 'Failed'), ('settings_changed', 'Settings changed'), ('viewed', 'Viewed'), ('denied', 'Denied')], max_length=32),
        ),
    ]
