# Generated by Django 6.1 on 2026-09-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_action_item_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamReading',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('observed_at', models.DateTimeField()),
            ],
        ),
    ]
