# Generated by Django 6.1 on 2026-09-24 00:40

from django.db import migrations, models


def forget_fingerprint_marks(apps, schema_editor):
    # Marks were keyed by a hash of an item's content, which no item key matches.
    apps.get_model("core", "ActionItemRead").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_upstream_reading'),
    ]

    operations = [
        migrations.RunPython(forget_fingerprint_marks, migrations.RunPython.noop),
        migrations.AddField(
            model_name='actionitemread',
            name='revision',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='actionitemread',
            name='key',
            field=models.CharField(max_length=200),
        ),
    ]
