# Generated by Django 6.1 on 2026-09-26 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_action_item_read_by_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='connection',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('uploaded', 'Uploaded'), ('exported', 'Exported'), ('imported', 'Imported'), ('failed', 'Failed'), ('settings_changed', 'Settings changed'), ('viewed', 'Viewed'), ('denied', 'Denied'), ('observed', 'Observed')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['connection', '-created_at'], name='core_auditl_connect_7a57b0_idx'),
        ),
    ]
