# Generated by Django 5.2.14 on 2026-05-16 20:13

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('networking', 'Networking gear'), ('server_hardware', 'Server hardware'), ('software', 'Software'), ('subscription', 'Subscription'), ('domain', 'Domain'), ('hosting', 'Hosting'), ('camera_audio', 'Camera / audio'), ('office', 'Office equipment'), ('tools', 'Tools'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('business_use_percentage', models.PositiveSmallIntegerField(default=100, help_text='0-100. Multiplied into total_cost to estimate deductible amount.')),
                ('estimated_deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated from total_cost × business_use_percentage / 100. Estimate only — not tax advice.', max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('debit', 'Debit card'), ('credit', 'Credit card'), ('ach', 'ACH / bank transfer'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('sold', 'Sold'), ('returned', 'Returned'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('related_projects', models.ManyToManyField(blank=True, related_name='assets', to='projects.project')),
            ],
            options={
                'ordering': ('-purchase_date', 'item_name'),
                'indexes': [models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'), models.Index(fields=['category'], name='assets_asse_categor_f3ee6a_idx'), models.Index(fields=['-purchase_date'], name='assets_asse_purchas_454a0a_idx')],
            },
        ),
    ]
