# Generated by Django 5.2.14 on 2026-05-16 20:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('content', '0001_initial'),
        ('docs_index', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('vendor', models.CharField(max_length=160)),
                ('item', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hosting', 'Hosting'), ('domains', 'Domains'), ('software', 'Software'), ('hardware', 'Hardware'), ('networking', 'Networking gear'), ('office', 'Office equipment'), ('education', 'Education / training'), ('subscriptions', 'Subscriptions'), ('content_production', 'Content production'), ('consulting_tools', 'Consulting tools'), ('professional_services', 'Professional services'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=32)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('business_use_percentage', models.PositiveSmallIntegerField(default=100, help_text='0-100. Used to estimate the deductible amount.')),
                ('estimated_deductible_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated. Estimate only — not tax advice.', max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('debit', 'Debit card'), ('credit', 'Credit card'), ('ach', 'ACH / bank transfer'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('business_purpose', models.CharField(blank=True, help_text='Short justification of the business reason for this expense.', max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('related_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='assets.asset')),
                ('related_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='content.contentitem')),
                ('related_documentation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='docs_index.documentationrecord')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'indexes': [models.Index(fields=['-date'], name='expenses_ex_date_2850f8_idx'), models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx'), models.Index(fields=['vendor'], name='expenses_ex_vendor_9d801d_idx')],
            },
        ),
    ]
