// Package connections provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package connections

// ACME The settings a connection of the acme shape arrives with.
type ACME struct {
	DirectoryURL string `json:"directory_url" setting:"DIRECTORY_URL"`
	Email        string `json:"email" setting:"EMAIL"`
}

// APIToken The settings a connection of the api_token shape arrives with.
type APIToken struct {
	APIToken string `json:"api_token" secret:"true" setting:"API_TOKEN"`
	URL      string `json:"url" setting:"URL"`
}

// Connection One connection: its reference, the provider it is for, whether HQ may change things through it, where its credential is kept, and its settings under the one shape it arrived in.
type Connection struct {
	// ACME The settings a connection of the acme shape arrives with.
	ACME *ACME `json:"acme,omitempty"`

	// APIToken The settings a connection of the api_token shape arrives with.
	APIToken *APIToken `json:"api_token,omitempty"`

	// GitHubApp The settings a connection of the github_app shape arrives with.
	GitHubApp *GitHubApp `json:"github_app,omitempty"`

	// Login The settings a connection of the login shape arrives with.
	Login   *Login `json:"login,omitempty"`
	Manages bool   `json:"manages"`

	// OAuthClient The settings a connection of the oauth_client shape arrives with.
	OAuthClient *OAuthClient `json:"oauth_client,omitempty"`
	Provider    string       `json:"provider"`
	Ref         string       `json:"ref"`

	// ServiceAccount The settings a connection of the service_account shape arrives with.
	ServiceAccount *ServiceAccount `json:"service_account,omitempty"`

	// SSHTransport The settings a connection of the ssh_transport shape arrives with.
	SSHTransport *SSHTransport `json:"ssh_transport,omitempty"`

	// Store Where a connection's credential is kept, as references only: the vault, the item, and the bootstrap item a replacement is minted with.
	Store Store `json:"store"`
}

// Document Every connection the controller may open.
type Document struct {
	Connections   []Connection `json:"connections"`
	SchemaVersion int          `json:"schema_version"`
}

// GitHubApp The settings a connection of the github_app shape arrives with.
type GitHubApp struct {
	AppID      string `json:"app_id" setting:"APP_ID"`
	SigningKey string `json:"signing_key" setting:"SIGNING_KEY"`
}

// Login The settings a connection of the login shape arrives with.
type Login struct {
	Password string `json:"password" secret:"true" setting:"PASSWORD"`
	URL      string `json:"url" setting:"URL"`
	Username string `json:"username" setting:"USERNAME"`
}

// OAuthClient The settings a connection of the oauth_client shape arrives with.
type OAuthClient struct {
	ClientID     string `json:"client_id" setting:"CLIENT_ID"`
	ClientSecret string `json:"client_secret" secret:"true" setting:"CLIENT_SECRET"`
}

// SSHTransport The settings a connection of the ssh_transport shape arrives with.
type SSHTransport struct {
	Host     string `json:"host" setting:"HOST"`
	HostKey  string `json:"host_key" setting:"HOST_KEY"`
	Identity string `json:"identity" setting:"IDENTITY"`
	Port     string `json:"port" setting:"PORT"`
	Role     string `json:"role,omitempty" setting:"ROLE"`
	User     string `json:"user" setting:"USER"`
}

// ServiceAccount The settings a connection of the service_account shape arrives with.
type ServiceAccount struct {
	APIToken string `json:"api_token" secret:"true" setting:"API_TOKEN"`
}

// Store Where a connection's credential is kept, as references only: the vault, the item, and the bootstrap item a replacement is minted with.
type Store struct {
	Bootstrap string `json:"bootstrap,omitempty"`
	Item      string `json:"item"`
	Vault     string `json:"vault"`
}
