// Package npmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package npmapi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for Directive.
const (
	Allow Directive = "allow"
	Deny  Directive = "deny"
)

// Valid indicates whether the value is a known member of the Directive enum.
func (e Directive) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// Defines values for ForwardScheme.
const (
	ForwardSchemeHttp  ForwardScheme = "http"
	ForwardSchemeHttps ForwardScheme = "https"
)

// Valid indicates whether the value is a known member of the ForwardScheme enum.
func (e ForwardScheme) Valid() bool {
	switch e {
	case ForwardSchemeHttp:
		return true
	case ForwardSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for ForwardScheme2.
const (
	ForwardScheme2Auto  ForwardScheme2 = "auto"
	ForwardScheme2Http  ForwardScheme2 = "http"
	ForwardScheme2Https ForwardScheme2 = "https"
)

// Valid indicates whether the value is a known member of the ForwardScheme2 enum.
func (e ForwardScheme2) Valid() bool {
	switch e {
	case ForwardScheme2Auto:
		return true
	case ForwardScheme2Http:
		return true
	case ForwardScheme2Https:
		return true
	default:
		return false
	}
}

// Defines values for MetaKeyType.
const (
	Ecdsa MetaKeyType = "ecdsa"
	Rsa   MetaKeyType = "rsa"
)

// Valid indicates whether the value is a known member of the MetaKeyType enum.
func (e MetaKeyType) Valid() bool {
	switch e {
	case Ecdsa:
		return true
	case Rsa:
		return true
	default:
		return false
	}
}

// Defines values for ProxyHostObjectForwardScheme.
const (
	ProxyHostObjectForwardSchemeHttp  ProxyHostObjectForwardScheme = "http"
	ProxyHostObjectForwardSchemeHttps ProxyHostObjectForwardScheme = "https"
)

// Valid indicates whether the value is a known member of the ProxyHostObjectForwardScheme enum.
func (e ProxyHostObjectForwardScheme) Valid() bool {
	switch e {
	case ProxyHostObjectForwardSchemeHttp:
		return true
	case ProxyHostObjectForwardSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for RedirectionHostObjectForwardScheme.
const (
	RedirectionHostObjectForwardSchemeAuto  RedirectionHostObjectForwardScheme = "auto"
	RedirectionHostObjectForwardSchemeHttp  RedirectionHostObjectForwardScheme = "http"
	RedirectionHostObjectForwardSchemeHttps RedirectionHostObjectForwardScheme = "https"
)

// Valid indicates whether the value is a known member of the RedirectionHostObjectForwardScheme enum.
func (e RedirectionHostObjectForwardScheme) Valid() bool {
	switch e {
	case RedirectionHostObjectForwardSchemeAuto:
		return true
	case RedirectionHostObjectForwardSchemeHttp:
		return true
	case RedirectionHostObjectForwardSchemeHttps:
		return true
	default:
		return false
	}
}

// Defines values for GetAccessListsParamsExpand.
const (
	GetAccessListsParamsExpandClients    GetAccessListsParamsExpand = "clients"
	GetAccessListsParamsExpandItems      GetAccessListsParamsExpand = "items"
	GetAccessListsParamsExpandOwner      GetAccessListsParamsExpand = "owner"
	GetAccessListsParamsExpandProxyHosts GetAccessListsParamsExpand = "proxy_hosts"
)

// Valid indicates whether the value is a known member of the GetAccessListsParamsExpand enum.
func (e GetAccessListsParamsExpand) Valid() bool {
	switch e {
	case GetAccessListsParamsExpandClients:
		return true
	case GetAccessListsParamsExpandItems:
		return true
	case GetAccessListsParamsExpandOwner:
		return true
	case GetAccessListsParamsExpandProxyHosts:
		return true
	default:
		return false
	}
}

// Defines values for GetCertificatesParamsExpand.
const (
	GetCertificatesParamsExpandOwner GetCertificatesParamsExpand = "owner"
)

// Valid indicates whether the value is a known member of the GetCertificatesParamsExpand enum.
func (e GetCertificatesParamsExpand) Valid() bool {
	switch e {
	case GetCertificatesParamsExpandOwner:
		return true
	default:
		return false
	}
}

// Defines values for GetDeadHostsParamsExpand.
const (
	GetDeadHostsParamsExpandCertificate GetDeadHostsParamsExpand = "certificate"
	GetDeadHostsParamsExpandOwner       GetDeadHostsParamsExpand = "owner"
)

// Valid indicates whether the value is a known member of the GetDeadHostsParamsExpand enum.
func (e GetDeadHostsParamsExpand) Valid() bool {
	switch e {
	case GetDeadHostsParamsExpandCertificate:
		return true
	case GetDeadHostsParamsExpandOwner:
		return true
	default:
		return false
	}
}

// Defines values for GetProxyHostsParamsExpand.
const (
	GetProxyHostsParamsExpandAccessList  GetProxyHostsParamsExpand = "access_list"
	GetProxyHostsParamsExpandCertificate GetProxyHostsParamsExpand = "certificate"
	GetProxyHostsParamsExpandOwner       GetProxyHostsParamsExpand = "owner"
)

// Valid indicates whether the value is a known member of the GetProxyHostsParamsExpand enum.
func (e GetProxyHostsParamsExpand) Valid() bool {
	switch e {
	case GetProxyHostsParamsExpandAccessList:
		return true
	case GetProxyHostsParamsExpandCertificate:
		return true
	case GetProxyHostsParamsExpandOwner:
		return true
	default:
		return false
	}
}

// Defines values for GetRedirectionHostsParamsExpand.
const (
	GetRedirectionHostsParamsExpandCertificate GetRedirectionHostsParamsExpand = "certificate"
	GetRedirectionHostsParamsExpandOwner       GetRedirectionHostsParamsExpand = "owner"
)

// Valid indicates whether the value is a known member of the GetRedirectionHostsParamsExpand enum.
func (e GetRedirectionHostsParamsExpand) Valid() bool {
	switch e {
	case GetRedirectionHostsParamsExpandCertificate:
		return true
	case GetRedirectionHostsParamsExpandOwner:
		return true
	default:
		return false
	}
}

// Defines values for GetStreamsParamsExpand.
const (
	GetStreamsParamsExpandCertificate GetStreamsParamsExpand = "certificate"
	GetStreamsParamsExpandOwner       GetStreamsParamsExpand = "owner"
)

// Valid indicates whether the value is a known member of the GetStreamsParamsExpand enum.
func (e GetStreamsParamsExpand) Valid() bool {
	switch e {
	case GetStreamsParamsExpandCertificate:
		return true
	case GetStreamsParamsExpandOwner:
		return true
	default:
		return false
	}
}

// Defines values for RequestTokenJSONBodyScope.
const (
	User RequestTokenJSONBodyScope = "user"
)

// Valid indicates whether the value is a known member of the RequestTokenJSONBodyScope enum.
func (e RequestTokenJSONBodyScope) Valid() bool {
	switch e {
	case User:
		return true
	default:
		return false
	}
}

// AccessListObject Access List object
type AccessListObject struct {
	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// Id Unique identifier
	Id   *Id             `json:"id,omitempty"`
	Meta json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`
	Name       string      `json:"name"`

	// OwnerUserId User ID
	OwnerUserId    UserId `json:"owner_user_id"`
	PassAuth       Flag   `json:"pass_auth"`
	ProxyHostCount int    `json:"proxy_host_count"`
	SatisfyAny     Flag   `json:"satisfy_any"`
}

// AccessClients defines model for access_clients.
type AccessClients = []struct {
	Address   *Address   `json:"address,omitempty"`
	Directive *Directive `json:"directive,omitempty"`
}

// AccessItems defines model for access_items.
type AccessItems = []struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// AccessListId Access List ID
type AccessListId = ID

// Address defines model for address.
type Address = string

// AdvancedConfig defines model for advanced_config.
type AdvancedConfig = string

// AllowWebsocketUpgrade Allow Websocket Upgrade for all paths
type AllowWebsocketUpgrade = Flag

// BlockExploits Should we block common exploits
type BlockExploits = Flag

// CachingEnabled Should we cache assets
type CachingEnabled = Flag

// CertificateList Certificates list
type CertificateList = []CertificateObject

// CertificateObject Certificate object
type CertificateObject struct {
	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames []string `json:"domain_names"`

	// ExpiresOn Date and time of expiration
	ExpiresOn *string `json:"expires_on,omitempty"`

	// Id Unique identifier
	Id   *Id             `json:"id,omitempty"`
	Meta json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`

	// NiceName Nice Name for the custom certificate
	NiceName string `json:"nice_name"`

	// Owner User object
	Owner *UserObject `json:"owner,omitempty"`

	// OwnerUserId User ID
	OwnerUserId UserId      `json:"owner_user_id"`
	Provider    SslProvider `json:"provider"`
}

// CertificateId Certificate ID
type CertificateId = ID

// CreatedOn Date and time of creation
type CreatedOn = string

// DeadHostList 404 Hosts list
type DeadHostList = []DeadHostObject

// DeadHostObject 404 Host object
type DeadHostObject struct {
	AdvancedConfig string             `json:"advanced_config"`
	Certificate    *CertificateObject `json:"certificate,omitempty"`

	// CertificateId Certificate ID
	CertificateId CertificateId `json:"certificate_id"`

	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// Enabled Is Enabled
	Enabled Enabled `json:"enabled"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled HstsEnabled `json:"hsts_enabled"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains HstsSubdomains `json:"hsts_subdomains"`

	// Http2Support HTTP2 Protocol Support
	Http2Support Http2Support `json:"http2_support"`

	// Id Unique identifier
	Id   *Id             `json:"id,omitempty"`
	Meta json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`

	// Owner User object
	Owner *UserObject `json:"owner,omitempty"`

	// OwnerUserId User ID
	OwnerUserId UserId `json:"owner_user_id"`

	// SslForced Is SSL Forced
	SslForced SslForced `json:"ssl_forced"`
}

// Directive defines model for directive.
type Directive string

// DnsProvidersList DNS Providers list
type DnsProvidersList = []struct {
	// Credentials Instructions on how to format the credentials for this DNS provider
	Credentials string `json:"credentials"`

	// Id Unique identifier for the DNS provider, matching the python package
	Id string `json:"id"`

	// Name Human-readable name of the DNS provider
	Name string `json:"name"`
}

// DomainNames Domain Names separated by a comma
type DomainNames = []string

// DomainNames2 Domain Names separated by a comma
type DomainNames2 = []string

// Enabled Is Enabled
type Enabled = Flag

// Error Error
type Error struct {
	// Error Error object
	Error *ErrorObject `json:"error,omitempty"`
}

// ErrorObject Error object
type ErrorObject struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ForwardDomainName Domain Name
type ForwardDomainName = string

// ForwardHost defines model for forward_host.
type ForwardHost = string

// ForwardHttpCode Redirect HTTP Status Code
type ForwardHttpCode = int

// ForwardPort defines model for forward_port.
type ForwardPort = int

// ForwardScheme defines model for forward_scheme.
type ForwardScheme string

// ForwardScheme2 defines model for forward_scheme-2.
type ForwardScheme2 string

// ForwardingHost defines model for forwarding_host.
type ForwardingHost = string

// ForwardingPort defines model for forwarding_port.
type ForwardingPort = int

// HstsEnabled Is HSTS Enabled
type HstsEnabled = Flag

// HstsSubdomains Is HSTS applicable to all subdomains
type HstsSubdomains = Flag

// Http2Support HTTP2 Protocol Support
type Http2Support = Flag

// Id Unique identifier
type Id = ID

// IncomingPort defines model for incoming_port.
type IncomingPort = int

// Locations defines model for locations.
type Locations = []struct {
	// AccessListId Access List ID
	AccessListId   *AccessListId `json:"access_list_id,omitempty"`
	AdvancedConfig *string       `json:"advanced_config,omitempty"`
	ForwardHost    ForwardHost   `json:"forward_host"`
	ForwardPath    *string       `json:"forward_path,omitempty"`
	ForwardPort    ForwardPort   `json:"forward_port"`
	ForwardScheme  ForwardScheme `json:"forward_scheme"`
	Id             *int          `json:"id,omitempty"`
	Path           string        `json:"path"`
}

// Meta defines model for meta.
type Meta struct {
	Certificate            *string                 `json:"certificate,omitempty"`
	CertificateKey         *string                 `json:"certificate_key,omitempty"`
	DnsChallenge           *Flag                   `json:"dns_challenge,omitempty"`
	DnsProvider            *string                 `json:"dns_provider,omitempty"`
	DnsProviderCredentials *string                 `json:"dns_provider_credentials,omitempty"`
	KeyType                *MetaKeyType            `json:"key_type,omitempty"`
	LetsencryptCertificate *map[string]interface{} `json:"letsencrypt_certificate,omitempty"`
	PropagationSeconds     *int                    `json:"propagation_seconds,omitempty"`
}

// MetaKeyType defines model for Meta.KeyType.
type MetaKeyType string

// Meta2 defines model for meta-2.
type Meta2 = map[string]interface{}

// Meta3 defines model for meta-3.
type Meta3 = map[string]interface{}

// ModifiedOn Date and time of last update
type ModifiedOn = string

// Name defines model for name.
type Name = string

// NiceName Nice Name for the custom certificate
type NiceName = string

// PassAuth defines model for pass_auth.
type PassAuth = Flag

// PreservePath Should the path be preserved
type PreservePath = Flag

// ProxyHostList Proxy Hosts list
type ProxyHostList = []ProxyHostObject

// ProxyHostObject Proxy Host object
type ProxyHostObject struct {
	AccessList *AccessListObject `json:"access_list,omitempty"`

	// AccessListId Access List ID
	AccessListId   AccessListId `json:"access_list_id"`
	AdvancedConfig string       `json:"advanced_config"`

	// AllowWebsocketUpgrade Allow Websocket Upgrade for all paths
	AllowWebsocketUpgrade Flag `json:"allow_websocket_upgrade"`

	// BlockExploits Should we block common exploits
	BlockExploits BlockExploits `json:"block_exploits"`

	// CachingEnabled Should we cache assets
	CachingEnabled CachingEnabled     `json:"caching_enabled"`
	Certificate    *CertificateObject `json:"certificate,omitempty"`

	// CertificateId Certificate ID
	CertificateId CertificateId `json:"certificate_id"`

	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// Enabled Is Enabled
	Enabled       Enabled                      `json:"enabled"`
	ForwardHost   string                       `json:"forward_host"`
	ForwardPort   int                          `json:"forward_port"`
	ForwardScheme ProxyHostObjectForwardScheme `json:"forward_scheme"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled HstsEnabled `json:"hsts_enabled"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains HstsSubdomains `json:"hsts_subdomains"`

	// Http2Support HTTP2 Protocol Support
	Http2Support Http2Support `json:"http2_support"`

	// Id Unique identifier
	Id        *Id             `json:"id,omitempty"`
	Locations json.RawMessage `json:"locations"`
	Meta      json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`

	// Owner User object
	Owner *UserObject `json:"owner,omitempty"`

	// OwnerUserId User ID
	OwnerUserId UserId `json:"owner_user_id"`

	// SslForced Is SSL Forced
	SslForced SslForced `json:"ssl_forced"`

	// TrustForwardedProto Trust the forwarded headers
	TrustForwardedProto Flag `json:"trust_forwarded_proto"`
}

// ProxyHostObjectForwardScheme defines model for ProxyHostObject.ForwardScheme.
type ProxyHostObjectForwardScheme string

// RedirectionHostList Redirection Hosts list
type RedirectionHostList = []RedirectionHostObject

// RedirectionHostObject Redirection Host object
type RedirectionHostObject struct {
	AdvancedConfig string `json:"advanced_config"`

	// BlockExploits Should we block common exploits
	BlockExploits BlockExploits      `json:"block_exploits"`
	Certificate   *CertificateObject `json:"certificate,omitempty"`

	// CertificateId Certificate ID
	CertificateId CertificateId `json:"certificate_id"`

	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// Enabled Is Enabled
	Enabled Enabled `json:"enabled"`

	// ForwardDomainName Domain Name
	ForwardDomainName string `json:"forward_domain_name"`

	// ForwardHttpCode Redirect HTTP Status Code
	ForwardHttpCode int                                `json:"forward_http_code"`
	ForwardScheme   RedirectionHostObjectForwardScheme `json:"forward_scheme"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled HstsEnabled `json:"hsts_enabled"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains HstsSubdomains `json:"hsts_subdomains"`

	// Http2Support HTTP2 Protocol Support
	Http2Support Http2Support `json:"http2_support"`

	// Id Unique identifier
	Id   *Id             `json:"id,omitempty"`
	Meta json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`

	// Owner User object
	Owner *UserObject `json:"owner,omitempty"`

	// OwnerUserId User ID
	OwnerUserId UserId `json:"owner_user_id"`

	// PreservePath Should the path be preserved
	PreservePath Flag `json:"preserve_path"`

	// SslForced Is SSL Forced
	SslForced SslForced `json:"ssl_forced"`
}

// RedirectionHostObjectForwardScheme defines model for RedirectionHostObject.ForwardScheme.
type RedirectionHostObjectForwardScheme string

// SatisfyAny defines model for satisfy_any.
type SatisfyAny = Flag

// SslForced Is SSL Forced
type SslForced = Flag

// SslProvider defines model for ssl_provider.
type SslProvider = string

// StreamList Streams list
type StreamList = []StreamObject

// StreamObject Stream object
type StreamObject struct {
	Certificate *CertificateObject `json:"certificate,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// CreatedOn Date and time of creation
	CreatedOn *CreatedOn `json:"created_on,omitempty"`

	// Enabled Is Enabled
	Enabled        Enabled `json:"enabled"`
	ForwardingHost string  `json:"forwarding_host"`
	ForwardingPort int     `json:"forwarding_port"`

	// Id Unique identifier
	Id           *Id             `json:"id,omitempty"`
	IncomingPort int             `json:"incoming_port"`
	Meta         json.RawMessage `json:"meta"`

	// ModifiedOn Date and time of last update
	ModifiedOn *ModifiedOn `json:"modified_on,omitempty"`

	// Owner User object
	Owner *UserObject `json:"owner,omitempty"`

	// OwnerUserId User ID
	OwnerUserId   UserId `json:"owner_user_id"`
	TcpForwarding Flag   `json:"tcp_forwarding"`
	UdpForwarding Flag   `json:"udp_forwarding"`
}

// TcpForwarding defines model for tcp_forwarding.
type TcpForwarding = Flag

// TokenChallenge Token object
type TokenChallenge struct {
	// ChallengeToken Challenge Token used in subsequent 2FA verification
	ChallengeToken string `json:"challenge_token"`

	// Requires2fa Whether this token request requires two-factor authentication
	Requires2fa Flag `json:"requires_2fa"`
}

// TokenObject Token object
type TokenObject struct {
	// Expires Token Expiry ISO Time String
	Expires string `json:"expires"`

	// Token JWT Token
	Token string `json:"token"`
}

// TrustForwardedProto Trust the forwarded headers
type TrustForwardedProto = Flag

// UdpForwarding defines model for udp_forwarding.
type UdpForwarding = Flag

// UserObject User object
type UserObject struct {
	// Avatar Gravatar URL based on email, without scheme
	Avatar string `json:"avatar"`

	// CreatedOn Created Date
	CreatedOn string `json:"created_on"`

	// Email Email
	Email string `json:"email"`

	// Id User ID
	Id int `json:"id"`

	// IsDisabled Is user Disabled
	IsDisabled Flag `json:"is_disabled"`

	// ModifiedOn Modified Date
	ModifiedOn string `json:"modified_on"`

	// Name Name
	Name string `json:"name"`

	// Nickname Nickname
	Nickname string `json:"nickname"`

	// Permissions Permissions if expanded in request
	Permissions *struct {
		// AccessLists Access Lists access level
		AccessLists string `json:"access_lists"`

		// Certificates Certificates access level
		Certificates string `json:"certificates"`

		// DeadHosts Dead Hosts access level
		DeadHosts string `json:"dead_hosts"`

		// ProxyHosts Proxy Hosts access level
		ProxyHosts string `json:"proxy_hosts"`

		// RedirectionHosts Redirection Hosts access level
		RedirectionHosts string `json:"redirection_hosts"`

		// Streams Streams access level
		Streams string `json:"streams"`

		// Visibility Visibility level
		Visibility string `json:"visibility"`
	} `json:"permissions,omitempty"`

	// Roles Roles applied
	Roles []string `json:"roles"`
}

// UserId User ID
type UserId = int

// GetAccessListsParams defines parameters for GetAccessLists.
type GetAccessListsParams struct {
	// Expand Expansions
	Expand *GetAccessListsParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetAccessListsParamsExpand defines parameters for GetAccessLists.
type GetAccessListsParamsExpand string

// CreateAccessListJSONBody defines parameters for CreateAccessList.
type CreateAccessListJSONBody struct {
	Clients    *AccessClients `json:"clients,omitempty"`
	Items      *AccessItems   `json:"items,omitempty"`
	Name       Name           `json:"name"`
	PassAuth   *PassAuth      `json:"pass_auth,omitempty"`
	SatisfyAny *SatisfyAny    `json:"satisfy_any,omitempty"`
}

// UpdateAccessListJSONBody defines parameters for UpdateAccessList.
type UpdateAccessListJSONBody struct {
	Clients    *AccessClients `json:"clients,omitempty"`
	Items      *AccessItems   `json:"items,omitempty"`
	Name       *Name          `json:"name,omitempty"`
	PassAuth   *PassAuth      `json:"pass_auth,omitempty"`
	SatisfyAny *SatisfyAny    `json:"satisfy_any,omitempty"`
}

// GetCertificatesParams defines parameters for GetCertificates.
type GetCertificatesParams struct {
	// Expand Expansions
	Expand *GetCertificatesParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetCertificatesParamsExpand defines parameters for GetCertificates.
type GetCertificatesParamsExpand string

// CreateCertificateJSONBody defines parameters for CreateCertificate.
type CreateCertificateJSONBody struct {
	// DomainNames Domain Names separated by a comma
	DomainNames *DomainNames     `json:"domain_names,omitempty"`
	Meta        *json.RawMessage `json:"meta,omitempty"`

	// NiceName Nice Name for the custom certificate
	NiceName *NiceName   `json:"nice_name,omitempty"`
	Provider SslProvider `json:"provider"`
}

// TestHttpReachJSONBody defines parameters for TestHttpReach.
type TestHttpReachJSONBody struct {
	// Domains Domain Names separated by a comma
	Domains DomainNames2 `json:"domains"`
}

// ValidateCertificatesMultipartBody defines parameters for ValidateCertificates.
type ValidateCertificatesMultipartBody struct {
	Certificate             string  `json:"certificate"`
	CertificateKey          string  `json:"certificate_key"`
	IntermediateCertificate *string `json:"intermediate_certificate,omitempty"`
}

// UploadCertificateMultipartBody defines parameters for UploadCertificate.
type UploadCertificateMultipartBody struct {
	Certificate             string  `json:"certificate"`
	CertificateKey          string  `json:"certificate_key"`
	IntermediateCertificate *string `json:"intermediate_certificate,omitempty"`
}

// GetDeadHostsParams defines parameters for GetDeadHosts.
type GetDeadHostsParams struct {
	// Expand Expansions
	Expand *GetDeadHostsParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetDeadHostsParamsExpand defines parameters for GetDeadHosts.
type GetDeadHostsParamsExpand string

// Create404HostJSONBody defines parameters for Create404Host.
type Create404HostJSONBody struct {
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`
}

// UpdateDeadHostJSONBody defines parameters for UpdateDeadHost.
type UpdateDeadHostJSONBody struct {
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames *DomainNames2 `json:"domain_names,omitempty"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`
}

// GetProxyHostsParams defines parameters for GetProxyHosts.
type GetProxyHostsParams struct {
	// Expand Expansions
	Expand *GetProxyHostsParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetProxyHostsParamsExpand defines parameters for GetProxyHosts.
type GetProxyHostsParamsExpand string

// CreateProxyHostJSONBody defines parameters for CreateProxyHost.
type CreateProxyHostJSONBody struct {
	// AccessListId Access List ID
	AccessListId   *AccessListId   `json:"access_list_id,omitempty"`
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// AllowWebsocketUpgrade Allow Websocket Upgrade for all paths
	AllowWebsocketUpgrade *AllowWebsocketUpgrade `json:"allow_websocket_upgrade,omitempty"`

	// BlockExploits Should we block common exploits
	BlockExploits *BlockExploits `json:"block_exploits,omitempty"`

	// CachingEnabled Should we cache assets
	CachingEnabled *CachingEnabled `json:"caching_enabled,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// Enabled Is Enabled
	Enabled       *Enabled      `json:"enabled,omitempty"`
	ForwardHost   ForwardHost   `json:"forward_host"`
	ForwardPort   ForwardPort   `json:"forward_port"`
	ForwardScheme ForwardScheme `json:"forward_scheme"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Locations    *Locations       `json:"locations,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`

	// TrustForwardedProto Trust the forwarded headers
	TrustForwardedProto *TrustForwardedProto `json:"trust_forwarded_proto,omitempty"`
}

// UpdateProxyHostJSONBody defines parameters for UpdateProxyHost.
type UpdateProxyHostJSONBody struct {
	// AccessListId Access List ID
	AccessListId   *AccessListId   `json:"access_list_id,omitempty"`
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// AllowWebsocketUpgrade Allow Websocket Upgrade for all paths
	AllowWebsocketUpgrade *AllowWebsocketUpgrade `json:"allow_websocket_upgrade,omitempty"`

	// BlockExploits Should we block common exploits
	BlockExploits *BlockExploits `json:"block_exploits,omitempty"`

	// CachingEnabled Should we cache assets
	CachingEnabled *CachingEnabled `json:"caching_enabled,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames *DomainNames2 `json:"domain_names,omitempty"`

	// Enabled Is Enabled
	Enabled       *Enabled       `json:"enabled,omitempty"`
	ForwardHost   *ForwardHost   `json:"forward_host,omitempty"`
	ForwardPort   *ForwardPort   `json:"forward_port,omitempty"`
	ForwardScheme *ForwardScheme `json:"forward_scheme,omitempty"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Locations    *Locations       `json:"locations,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`

	// TrustForwardedProto Trust the forwarded headers
	TrustForwardedProto *TrustForwardedProto `json:"trust_forwarded_proto,omitempty"`
}

// GetRedirectionHostsParams defines parameters for GetRedirectionHosts.
type GetRedirectionHostsParams struct {
	// Expand Expansions
	Expand *GetRedirectionHostsParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetRedirectionHostsParamsExpand defines parameters for GetRedirectionHosts.
type GetRedirectionHostsParamsExpand string

// CreateRedirectionHostJSONBody defines parameters for CreateRedirectionHost.
type CreateRedirectionHostJSONBody struct {
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// BlockExploits Should we block common exploits
	BlockExploits *BlockExploits `json:"block_exploits,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames DomainNames2 `json:"domain_names"`

	// ForwardDomainName Domain Name
	ForwardDomainName ForwardDomainName `json:"forward_domain_name"`

	// ForwardHttpCode Redirect HTTP Status Code
	ForwardHttpCode ForwardHttpCode `json:"forward_http_code"`
	ForwardScheme   ForwardScheme2  `json:"forward_scheme"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// PreservePath Should the path be preserved
	PreservePath *PreservePath `json:"preserve_path,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`
}

// UpdateRedirectionHostJSONBody defines parameters for UpdateRedirectionHost.
type UpdateRedirectionHostJSONBody struct {
	AdvancedConfig *AdvancedConfig `json:"advanced_config,omitempty"`

	// BlockExploits Should we block common exploits
	BlockExploits *BlockExploits `json:"block_exploits,omitempty"`

	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames *DomainNames2 `json:"domain_names,omitempty"`

	// ForwardDomainName Domain Name
	ForwardDomainName *ForwardDomainName `json:"forward_domain_name,omitempty"`

	// ForwardHttpCode Redirect HTTP Status Code
	ForwardHttpCode *ForwardHttpCode `json:"forward_http_code,omitempty"`
	ForwardScheme   *ForwardScheme2  `json:"forward_scheme,omitempty"`

	// HstsEnabled Is HSTS Enabled
	HstsEnabled *HstsEnabled `json:"hsts_enabled,omitempty"`

	// HstsSubdomains Is HSTS applicable to all subdomains
	HstsSubdomains *HstsSubdomains `json:"hsts_subdomains,omitempty"`

	// Http2Support HTTP2 Protocol Support
	Http2Support *Http2Support    `json:"http2_support,omitempty"`
	Meta         *json.RawMessage `json:"meta,omitempty"`

	// PreservePath Should the path be preserved
	PreservePath *PreservePath `json:"preserve_path,omitempty"`

	// SslForced Is SSL Forced
	SslForced *SslForced `json:"ssl_forced,omitempty"`
}

// GetStreamsParams defines parameters for GetStreams.
type GetStreamsParams struct {
	// Expand Expansions
	Expand *GetStreamsParamsExpand `form:"expand,omitempty" json:"expand,omitempty"`
}

// GetStreamsParamsExpand defines parameters for GetStreams.
type GetStreamsParamsExpand string

// CreateStreamJSONBody defines parameters for CreateStream.
type CreateStreamJSONBody struct {
	// CertificateId Certificate ID
	CertificateId *CertificateId `json:"certificate_id,omitempty"`

	// DomainNames Domain Names separated by a comma
	DomainNames    *DomainNames2    `json:"domain_names,omitempty"`
	ForwardingHost ForwardingHost   `json:"forwarding_host"`
	ForwardingPort ForwardingPort   `json:"forwarding_port"`
	IncomingPort   IncomingPort     `json:"incoming_port"`
	Meta           *json.RawMessage `json:"meta,omitempty"`
	TcpForwarding  *TcpForwarding   `json:"tcp_forwarding,omitempty"`
	UdpForwarding  *UdpForwarding   `json:"udp_forwarding,omitempty"`
}

// UpdateStreamJSONBody defines parameters for UpdateStream.
type UpdateStreamJSONBody struct {
	// CertificateId Certificate ID
	CertificateId  *CertificateId   `json:"certificate_id,omitempty"`
	ForwardingHost *ForwardingHost  `json:"forwarding_host,omitempty"`
	ForwardingPort *ForwardingPort  `json:"forwarding_port,omitempty"`
	IncomingPort   *IncomingPort    `json:"incoming_port,omitempty"`
	Meta           *json.RawMessage `json:"meta,omitempty"`
	TcpForwarding  *TcpForwarding   `json:"tcp_forwarding,omitempty"`
	UdpForwarding  *UdpForwarding   `json:"udp_forwarding,omitempty"`
}

// RequestTokenJSONBody defines parameters for RequestToken.
type RequestTokenJSONBody struct {
	Identity string                     `json:"identity"`
	Scope    *RequestTokenJSONBodyScope `json:"scope,omitempty"`
	Secret   string                     `json:"secret"`
}

// RequestTokenJSONBodyScope defines parameters for RequestToken.
type RequestTokenJSONBodyScope string

// RequestToken200JSONResponseBody defines parameters for RequestToken.
type RequestToken200JSONResponseBody struct {
	union json.RawMessage
}

// LoginWith2FAJSONBody defines parameters for LoginWith2FA.
type LoginWith2FAJSONBody struct {
	ChallengeToken string `json:"challenge_token"`
	Code           string `json:"code"`
}

// CreateAccessListJSONRequestBody defines body for CreateAccessList for application/json ContentType.
type CreateAccessListJSONRequestBody CreateAccessListJSONBody

// UpdateAccessListJSONRequestBody defines body for UpdateAccessList for application/json ContentType.
type UpdateAccessListJSONRequestBody UpdateAccessListJSONBody

// CreateCertificateJSONRequestBody defines body for CreateCertificate for application/json ContentType.
type CreateCertificateJSONRequestBody CreateCertificateJSONBody

// TestHttpReachJSONRequestBody defines body for TestHttpReach for application/json ContentType.
type TestHttpReachJSONRequestBody TestHttpReachJSONBody

// ValidateCertificatesMultipartRequestBody defines body for ValidateCertificates for multipart/form-data ContentType.
type ValidateCertificatesMultipartRequestBody ValidateCertificatesMultipartBody

// UploadCertificateMultipartRequestBody defines body for UploadCertificate for multipart/form-data ContentType.
type UploadCertificateMultipartRequestBody UploadCertificateMultipartBody

// Create404HostJSONRequestBody defines body for Create404Host for application/json ContentType.
type Create404HostJSONRequestBody Create404HostJSONBody

// UpdateDeadHostJSONRequestBody defines body for UpdateDeadHost for application/json ContentType.
type UpdateDeadHostJSONRequestBody UpdateDeadHostJSONBody

// CreateProxyHostJSONRequestBody defines body for CreateProxyHost for application/json ContentType.
type CreateProxyHostJSONRequestBody CreateProxyHostJSONBody

// UpdateProxyHostJSONRequestBody defines body for UpdateProxyHost for application/json ContentType.
type UpdateProxyHostJSONRequestBody UpdateProxyHostJSONBody

// CreateRedirectionHostJSONRequestBody defines body for CreateRedirectionHost for application/json ContentType.
type CreateRedirectionHostJSONRequestBody CreateRedirectionHostJSONBody

// UpdateRedirectionHostJSONRequestBody defines body for UpdateRedirectionHost for application/json ContentType.
type UpdateRedirectionHostJSONRequestBody UpdateRedirectionHostJSONBody

// CreateStreamJSONRequestBody defines body for CreateStream for application/json ContentType.
type CreateStreamJSONRequestBody CreateStreamJSONBody

// UpdateStreamJSONRequestBody defines body for UpdateStream for application/json ContentType.
type UpdateStreamJSONRequestBody UpdateStreamJSONBody

// RequestTokenJSONRequestBody defines body for RequestToken for application/json ContentType.
type RequestTokenJSONRequestBody RequestTokenJSONBody

// LoginWith2FAJSONRequestBody defines body for LoginWith2FA for application/json ContentType.
type LoginWith2FAJSONRequestBody LoginWith2FAJSONBody

// AsTokenObject returns the union data inside the RequestToken200JSONResponseBody as a TokenObject
func (t RequestToken200JSONResponseBody) AsTokenObject() (TokenObject, error) {
	var body TokenObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTokenObject overwrites any union data inside the RequestToken200JSONResponseBody as the provided TokenObject
func (t *RequestToken200JSONResponseBody) FromTokenObject(v TokenObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTokenObject performs a merge with any union data inside the RequestToken200JSONResponseBody, using the provided TokenObject
func (t *RequestToken200JSONResponseBody) MergeTokenObject(v TokenObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTokenChallenge returns the union data inside the RequestToken200JSONResponseBody as a TokenChallenge
func (t RequestToken200JSONResponseBody) AsTokenChallenge() (TokenChallenge, error) {
	var body TokenChallenge
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTokenChallenge overwrites any union data inside the RequestToken200JSONResponseBody as the provided TokenChallenge
func (t *RequestToken200JSONResponseBody) FromTokenChallenge(v TokenChallenge) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTokenChallenge performs a merge with any union data inside the RequestToken200JSONResponseBody, using the provided TokenChallenge
func (t *RequestToken200JSONResponseBody) MergeTokenChallenge(v TokenChallenge) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RequestToken200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RequestToken200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
