# Generated by Django 6.1 on 2026-09-25 22:31

import receipts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(help_text='PDF or image. Private to signed-in users.', storage=receipts.storage.PrivateReceiptStorage(), upload_to=receipts.storage.receipt_upload_path),
        ),
    ]
