# Generated by Django 6.1 on 2026-09-25 22:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='business_purpose',
            field=models.CharField(blank=True, help_text='Why this is a business expense, in one line.', max_length=300),
        ),
        migrations.AlterField(
            model_name='expense',
            name='estimated_deductible_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculated on save. Estimate, not tax advice.', max_digits=12),
        ),
    ]
