# Generated by Django 6.1 on 2026-08-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0008_certificate_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatematerial',
            name='domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
