# Generated by Django 6.1 on 2026-08-20 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0009_certificate_material_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_ref', models.CharField(max_length=160)),
                ('controller_id', models.CharField(blank=True, max_length=160)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('reaches', models.JSONField(blank=True, default=list)),
                ('reachable', models.BooleanField(default=True)),
                ('probed', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('observed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('provider', 'connection_ref'),
                'constraints': [models.UniqueConstraint(fields=('controller_id', 'connection_ref'), name='one_row_per_connection_per_controller')],
            },
        ),
    ]
