# Generated by Django 6.1 on 2026-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0022_machine_telemetry_is_a_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinventory',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
