# Generated by Django 6.1 on 2026-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0023_provider_inventory_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinventory',
            name='refusal',
            field=models.CharField(blank=True, choices=[('credential', 'credential'), ('permission', 'permission')], max_length=16),
        ),
    ]
