# Generated by Django 6.1 on 2026-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0027_connection_credential_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconnection',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
