# Generated by Django 6.1 on 2026-08-20 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_operation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(max_length=64)),
                ('target_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('target_key',),
                'indexes': [models.Index(fields=['user', 'target_kind'], name='core_pin_user_id_a7fbef_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_kind', 'target_key'), name='unique_pin')],
            },
        ),
    ]
