# Generated by Django 6.1 on 2026-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ('position', 'target_key')},
        ),
        migrations.AddField(
            model_name='pin',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
