# Generated by Django 6.1.1 on 2026-10-03 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_appearance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(max_length=32)),
                ("image", models.BinaryField()),
                ("digest", models.CharField(max_length=64)),
                ("source", models.CharField(max_length=500)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="avatar", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
