# Generated by Django 6.1.1 on 2026-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revision",
            fields=[
                ("name", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("value", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
