# Generated by Django 6.1.1 on 2026-10-04 21:30

from django.conf import settings
from django.db import migrations, models

import hq.platform.core.rules


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agentaccess",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(("id", 1)),
                name="agent_access_is_one_row",
                violation_error_message="There is one of these, with id 1.",
            ),
        ),
    ]
