# Generated by Django 5.2.14 on 2026-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('docs_index', '0001_initial'),
        ('expenses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='related_documentation',
            field=models.ManyToManyField(blank=True, related_name='content_items', to='docs_index.documentationrecord'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='related_expenses',
            field=models.ManyToManyField(blank=True, related_name='content_items', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='content_items', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status'], name='content_con_status_c88a23_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type'], name='content_con_content_8fbc99_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['published_at'], name='content_con_publish_5be4f6_idx'),
        ),
    ]
