# Generated by Django 5.2.14 on 2026-05-16 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_id', models.SlugField(help_text="Stable identifier, e.g. 'rb-adguard-001'. Used by the future knowledge-router MCP and JSON exports.", max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('runbook', 'Runbook'), ('architecture_note', 'Architecture note'), ('deployment_guide', 'Deployment guide'), ('troubleshooting_guide', 'Troubleshooting guide'), ('recovery_procedure', 'Recovery procedure'), ('public_article_draft', 'Public article draft'), ('decision_record', 'Decision record')], default='runbook', max_length=32)),
                ('system_service', models.CharField(blank=True, help_text="System or service the doc is about, e.g. 'AdGuard Home'.", max_length=120)),
                ('environment', models.CharField(choices=[('homelab', 'Homelab'), ('vps', 'VPS'), ('wordpress', 'WordPress'), ('cloudflare', 'Cloudflare'), ('tailscale', 'Tailscale'), ('adguard', 'AdGuard'), ('unifi', 'UniFi'), ('local_mac', 'Local Mac'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('sensitive', 'Sensitive'), ('secret_adjacent', 'Secret-adjacent')], default='internal', help_text='Sensitivity label. Public/internal docs can be referenced by the future MCP; sensitive/secret-adjacent should not be.', max_length=20)),
                ('obsidian_path', models.CharField(blank=True, help_text="Path inside the Obsidian vault, e.g. 'Infra/DNS/AdGuard Home.md'.", max_length=400)),
                ('github_path', models.CharField(blank=True, help_text='Repo-relative path if this doc also lives in a Git repo.', max_length=400)),
                ('external_url', models.URLField(blank=True)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Index-level notes only. Do not paste runbook contents here.')),
                ('related_assets', models.ManyToManyField(blank=True, related_name='documentation_records', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Documentation record',
                'ordering': ('-updated_at',),
            },
        ),
    ]
