# Generated by Django 5.2.14 on 2026-06-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_index', '0004_documentationrecord_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationrecord',
            name='doc_type',
            field=models.CharField(choices=[('runbook', 'Runbook'), ('architecture_note', 'Architecture note'), ('deployment_guide', 'Deployment guide'), ('troubleshooting_guide', 'Troubleshooting guide'), ('recovery_procedure', 'Recovery procedure'), ('public_article_draft', 'Public article draft'), ('decision_record', 'Decision record'), ('task', 'Task')], default='runbook', max_length=32),
        ),
    ]
