# Generated by Django 6.1 on 2026-09-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_index', '0006_alter_documentationrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationrecord',
            name='doc_id',
            field=models.SlugField(help_text="Stable identifier, e.g. 'rb-adguard-001'. Never rename it.", max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='documentationrecord',
            name='sensitivity',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('sensitive', 'Sensitive'), ('restricted', 'Restricted')], default='internal', help_text='Public and internal docs are safe for AI export. Sensitive and restricted are not.', max_length=20),
        ),
    ]
