# Generated by Django 6.1.1 on 2026-10-04 21:30

import hq.platform.core.rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_business_use_in_range'),
        ('docs_index', '0007_help_text_copy'),
        ('expenses', '0003_business_use_in_range'),
        ('projects', '0002_project_last_push_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentationrecord',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('doc_type', 'task'), ('status__in', ['open', 'active', 'parked', 'done', 'wontfix'])), models.Q(models.Q(('doc_type', 'task'), _negated=True), ('status__in', ['draft', 'active', 'deprecated', 'archived'])), _connector='OR'), field='status', name='documentation_status_fits_its_type', violation_error_message='A task is one of: open, active, parked, done, wontfix. Any other doc is one of: draft, active, deprecated, archived.'),
        ),
    ]
