# Generated by Django 6.1 on 2026-08-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_tag', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('connection_ref', models.CharField(blank=True, max_length=100)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('observed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('host',),
            },
        ),
        migrations.CreateModel(
            name='RumDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dimension', models.CharField(choices=[('path', 'Page'), ('referrer', 'Referrer'), ('country', 'Country'), ('device', 'Device'), ('browser', 'Browser'), ('os', 'Operating system')], max_length=16)),
                ('value', models.CharField(max_length=512)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('sample_interval', models.PositiveIntegerField(default=1)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='analytics.analyticssite')),
            ],
            options={
                'ordering': ('-date', '-pageviews'),
                'indexes': [models.Index(fields=['site', 'dimension', '-date'], name='analytics_r_site_id_9916d7_idx'), models.Index(fields=['dimension', 'value', '-date'], name='analytics_r_dimensi_e61cb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'date', 'dimension', 'value'), name='analytics_rumdaily_unique_grain')],
            },
        ),
        migrations.CreateModel(
            name='VitalsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('largest_contentful_paint_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('interaction_to_next_paint_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('first_contentful_paint_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('time_to_first_byte_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cumulative_layout_shift', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('lcp_good', models.PositiveIntegerField(default=0)),
                ('lcp_needs_improvement', models.PositiveIntegerField(default=0)),
                ('lcp_poor', models.PositiveIntegerField(default=0)),
                ('inp_good', models.PositiveIntegerField(default=0)),
                ('inp_needs_improvement', models.PositiveIntegerField(default=0)),
                ('inp_poor', models.PositiveIntegerField(default=0)),
                ('cls_good', models.PositiveIntegerField(default=0)),
                ('cls_needs_improvement', models.PositiveIntegerField(default=0)),
                ('cls_poor', models.PositiveIntegerField(default=0)),
                ('sample_interval', models.PositiveIntegerField(default=1)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='analytics.analyticssite')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('site', 'date'), name='analytics_vitalsdaily_unique_day')],
            },
        ),
    ]
