# Generated by Django 6.0.7 on 2026-07-25 06:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedResource',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(max_length=64)),
                ('spec', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('observed_generation', models.PositiveIntegerField(default=0)),
                ('status', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('kind', 'key'),
                'indexes': [models.Index(fields=['kind', 'enabled'], name='control_pla_kind_54bde2_idx'), models.Index(fields=['last_observed_at'], name='control_pla_last_ob_c9b7d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationRequest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('reconcile', 'Reconcile'), ('renew', 'Renew certificate'), ('delete', 'Delete')], max_length=20)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('requested_actor', models.CharField(max_length=160)),
                ('requested_interface', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('claimed_by', models.CharField(blank=True, max_length=160)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_operations', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='control_plane.managedresource')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', 'created_at'], name='control_pla_state_203acd_idx'), models.Index(fields=['resource', 'action', 'state'], name='control_pla_resourc_b8fd21_idx')],
            },
        ),
    ]
