# Generated by Django 6.1 on 2026-09-19 05:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0018_dashboard_supports_multiple_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resource_kind', models.CharField(blank=True, max_length=64)),
                ('resource_key', models.CharField(blank=True, max_length=180)),
                ('baseline', models.JSONField(blank=True, default=dict)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('requested_actor', models.CharField(max_length=160)),
                ('requested_interface', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('pending', 'Waiting for a person'), ('approved', 'Approved and applied'), ('rejected', 'Rejected'), ('expired', 'Lapsed unanswered'), ('stale', 'Superseded by a later change')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('decided_actor', models.CharField(blank=True, max_length=160)),
                ('decided_interface', models.CharField(blank=True, max_length=32)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['state', 'expires_at'], name='control_pla_state_c1b192_idx'), models.Index(fields=['resource_key', 'state'], name='control_pla_resourc_b4b669_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('capability', 'target', 'content_fingerprint'), name='one_pending_approval_per_requested_change')],
            },
        ),
    ]
