# Generated by Django 6.1 on 2026-09-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0024_provider_inventory_refusal'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconnection',
            name='manages',
            field=models.BooleanField(default=False),
        ),
    ]
