# Generated by Django 6.1 on 2026-09-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_plane", "0028_connection_reported_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerconnection",
            name="failure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("credential", "credential"),
                    ("permission", "permission"),
                    ("address", "address"),
                    ("network", "network"),
                ],
                max_length=16,
            ),
        ),
    ]
