# Generated by Django 6.1 on 2026-09-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0029_connection_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinventory',
            name='refused_parts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
