# Generated by Django 6.1.1 on 2026-10-04 21:33

import hq.platform.core.rules
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0031_read_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(('state__in', ['pending', 'approved', 'rejected', 'expired', 'stale'])), field='state', name='approval_state_is_declared', violation_error_message='Must be one of: pending, approved, rejected, expired, stale.'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('decided_at__isnull', True), ('state', 'pending')), models.Q(models.Q(('state', 'pending'), _negated=True), ('decided_at__isnull', False)), _connector='OR'), field='state', name='approval_settled_says_when', violation_error_message='A request has a decision time exactly when it is no longer pending.'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('state__in', ('approved', 'rejected')), models.Q(('decided_actor', ''), _negated=True)), models.Q(models.Q(('state__in', ('approved', 'rejected')), _negated=True), ('decided_actor', '')), _connector='OR'), field='state', name='approval_decision_names_who_decided', violation_error_message='An approval or a rejection names who decided it, and nothing else does.'),
        ),
        migrations.AddConstraint(
            model_name='dashboardconfiguration',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(('id', 1)), name='dashboard_configuration_is_one_row', violation_error_message='There is one of these, with id 1.'),
        ),
        migrations.AddConstraint(
            model_name='managedresource',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(('generation__gte', 1)), field='generation', name='resource_generation_starts_at_one', violation_error_message='A generation starts at 1.'),
        ),
        migrations.AddConstraint(
            model_name='managedresource',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(('observed_generation__lte', models.F('generation'))), field='observed_generation', name='resource_observed_no_later_than_declared', violation_error_message='A resource is observed at a generation it has reached.'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(('state__in', ['queued', 'claimed', 'succeeded', 'failed', 'cancelled'])), field='state', name='operation_state_is_declared', violation_error_message='Must be one of: queued, claimed, succeeded, failed, cancelled.'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('state', 'claimed'), _negated=True), models.Q(models.Q(('claimed_by', ''), _negated=True), ('lease_expires_at__isnull', False)), _connector='OR'), field='state', name='operation_claimed_names_its_claim', violation_error_message='A claimed operation names its controller and its lease.'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('state', 'queued'), _negated=True), models.Q(('claimed_at__isnull', True), ('claimed_by', ''), ('lease_expires_at__isnull', True)), _connector='OR'), field='state', name='operation_queued_has_no_claim', violation_error_message='A queued operation is claimed by nobody.'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=hq.platform.core.rules.Rule(condition=models.Q(models.Q(('completed_at__isnull', False), ('state__in', ('succeeded', 'failed', 'cancelled'))), models.Q(('completed_at__isnull', True), ('state__in', ('queued', 'claimed'))), _connector='OR'), field='state', name='operation_finished_says_when', violation_error_message='An operation has a completion time exactly when it has finished.'),
        ),
    ]
