# Generated by Django 6.1 on 2026-09-25 22:31

from hq.domains.receipts import storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(help_text='PDF or image. Private to signed-in users.', storage=storage.PrivateReceiptStorage(), upload_to=storage.receipt_upload_path),
        ),
    ]
