# Generated by Django 5.2.14 on 2026-05-16 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('lab_writeup', 'Lab writeup'), ('guide', 'Guide'), ('review', 'Review'), ('portfolio_page', 'Portfolio page'), ('service_page', 'Service page'), ('case_study', 'Case study')], default='article', max_length=24)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('researching', 'Researching'), ('drafting', 'Drafting'), ('editing', 'Editing'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags.', max_length=300)),
                ('published_url', models.URLField(blank=True)),
                ('wordpress_post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('wordpress_slug', models.SlugField(blank=True, max_length=200)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('related_assets', models.ManyToManyField(blank=True, related_name='content_items', to='assets.asset')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
