// Package runtime provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package runtime

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for AnalyticsRowDimension.
const (
	Browser  AnalyticsRowDimension = "browser"
	Country  AnalyticsRowDimension = "country"
	Device   AnalyticsRowDimension = "device"
	Os       AnalyticsRowDimension = "os"
	Path     AnalyticsRowDimension = "path"
	Referrer AnalyticsRowDimension = "referrer"
)

// Valid indicates whether the value is a known member of the AnalyticsRowDimension enum.
func (e AnalyticsRowDimension) Valid() bool {
	switch e {
	case Browser:
		return true
	case Country:
		return true
	case Device:
		return true
	case Os:
		return true
	case Path:
		return true
	case Referrer:
		return true
	default:
		return false
	}
}

// Defines values for AnalyticsWindowReason.
const (
	Backfill AnalyticsWindowReason = "backfill"
	Refresh  AnalyticsWindowReason = "refresh"
)

// Valid indicates whether the value is a known member of the AnalyticsWindowReason enum.
func (e AnalyticsWindowReason) Valid() bool {
	switch e {
	case Backfill:
		return true
	case Refresh:
		return true
	default:
		return false
	}
}

// Acknowledgement Django's answer to a report; the controller reads only ok.
type Acknowledgement struct {
	OK                   bool                   `json:"ok"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// AnalyticsPlan defines model for AnalyticsPlan.
type AnalyticsPlan struct {
	OK      bool              `json:"ok"`
	Windows []AnalyticsWindow `json:"windows"`
}

// AnalyticsReadings One controller's reading of every analytics site it can see (record_analytics).
type AnalyticsReadings struct {
	Sites []AnalyticsSiteReading `json:"sites"`
}

// AnalyticsRow One day's count for one value of one breakdown.
type AnalyticsRow struct {
	Date           *string               `json:"date"`
	Dimension      AnalyticsRowDimension `json:"dimension"`
	Pageviews      int                   `json:"pageviews"`
	SampleInterval int                   `json:"sample_interval"`
	Value          string                `json:"value"`
	Visits         int                   `json:"visits"`
}

// AnalyticsRowDimension defines model for AnalyticsRow.Dimension.
type AnalyticsRowDimension string

// AnalyticsSiteIdentity defines model for AnalyticsSiteIdentity.
type AnalyticsSiteIdentity struct {
	ConnectionRef string `json:"connection_ref"`
	SiteTag       string `json:"site_tag"`
}

// AnalyticsSiteReading One site's traffic and vitals over whole UTC days, start to end inclusive.
type AnalyticsSiteReading struct {
	ConnectionRef string            `json:"connection_ref"`
	End           string            `json:"end"`
	Host          string            `json:"host"`
	Rows          []AnalyticsRow    `json:"rows"`
	SiteTag       string            `json:"site_tag"`
	Start         string            `json:"start"`
	Vitals        []AnalyticsVitals `json:"vitals"`
}

// AnalyticsVitals One day's site-wide Core Web Vitals.
type AnalyticsVitals struct {
	ClsGood               int      `json:"cls_good"`
	ClsNeedsImprovement   int      `json:"cls_needs_improvement"`
	ClsPoor               int      `json:"cls_poor"`
	CumulativeLayoutShift *float64 `json:"cumulative_layout_shift"`
	Date                  *string  `json:"date"`

	// FirstContentfulPaintMs p75 in milliseconds; null when there were no samples.
	FirstContentfulPaintMs *int `json:"first_contentful_paint_ms"`
	InpGood                int  `json:"inp_good"`
	InpNeedsImprovement    int  `json:"inp_needs_improvement"`
	InpPoor                int  `json:"inp_poor"`

	// InteractionToNextPaintMs p75 in milliseconds; null when there were no samples.
	InteractionToNextPaintMs *int `json:"interaction_to_next_paint_ms"`

	// LargestContentfulPaintMs p75 in milliseconds; null when there were no samples.
	LargestContentfulPaintMs *int `json:"largest_contentful_paint_ms"`
	LcpGood                  int  `json:"lcp_good"`
	LcpNeedsImprovement      int  `json:"lcp_needs_improvement"`
	LcpPoor                  int  `json:"lcp_poor"`
	SampleInterval           int  `json:"sample_interval"`

	// TimeToFirstByteMs p75 in milliseconds; null when there were no samples.
	TimeToFirstByteMs *int `json:"time_to_first_byte_ms"`
}

// AnalyticsWindow defines model for AnalyticsWindow.
type AnalyticsWindow struct {
	ConnectionRef string                `json:"connection_ref"`
	End           string                `json:"end"`
	Reason        AnalyticsWindowReason `json:"reason"`
	SiteTag       string                `json:"site_tag"`
	Start         string                `json:"start"`
}

// AnalyticsWindowReason defines model for AnalyticsWindow.Reason.
type AnalyticsWindowReason string

// Capability defines model for Capability.
type Capability struct {
	Action string `json:"action"`
	Kind   string `json:"kind"`
}

// Condition defines model for Condition.
type Condition struct {
	Message string `json:"message"`
	Reason  string `json:"reason"`
	Status  bool   `json:"status"`
	Type    string `json:"type"`
}

// ConnectionRecord One connection the controller carries and what its probe found.
type ConnectionRecord struct {
	Carried       bool   `json:"carried,omitempty"`
	ConnectionRef string `json:"connection_ref"`
	Detail        string `json:"detail"`
	Endpoint      string `json:"endpoint"`

	// ExpiresAt Credential expiry the probe read, when it read one.
	ExpiresAt string   `json:"expires_at,omitempty"`
	Failure   string   `json:"failure,omitempty"`
	Manages   bool     `json:"manages"`
	OK        bool     `json:"ok"`
	Probed    bool     `json:"probed"`
	Provider  string   `json:"provider"`
	Reaches   []string `json:"reaches"`

	// Store Where the connection's credentials are stored, as connection_env reports it.
	Store any `json:"store,omitempty"`
}

// Contract The desired-only contract for one resource (export).
type Contract struct {
	Resource      Resource `json:"resource"`
	SchemaVersion int      `json:"schema_version"`
}

// ControllerRegistry What the controller may do and where each kind is read, from HQ's provider declarations.
type ControllerRegistry struct {
	// Capabilities Actions the controller may apply.
	Capabilities []Capability `json:"capabilities"`

	// ConnectionCredentials Providers a connection credential is modelled for.
	ConnectionCredentials []string `json:"connection_credentials"`

	// ConnectionProviders Each resource kind's connection providers.
	ConnectionProviders map[string][]string `json:"connection_providers"`
	Locked              []LockedAction      `json:"locked"`

	// MaterialKinds Kinds whose work needs material HQ holds.
	MaterialKinds []string `json:"material_kinds"`

	// Observations Each reading kind's provider.
	Observations map[string]string `json:"observations"`
	OK           bool              `json:"ok"`
}

// ControllerReport defines model for ControllerReport.
type ControllerReport struct {
	Conditions         []Condition `json:"conditions,omitempty"`
	Message            string      `json:"message,omitempty"`
	ObservedGeneration int64       `json:"observed_generation"`

	// Status The provider's status for the resource; its shape belongs to the kind.
	Status  any  `json:"status,omitempty"`
	Success bool `json:"success"`
}

// ForcedRead An operator's pending read request.
type ForcedRead struct {
	ConnectionRef string    `json:"connection_ref"`
	Kind          string    `json:"kind"`
	Kinds         []string  `json:"kinds"`
	RequestedAt   time.Time `json:"requested_at"`
}

// GlanceMachineTarget defines model for GlanceMachineTarget.
type GlanceMachineTarget struct {
	Connections []string `json:"connections"`
	Key         string   `json:"key"`
	RequestID   string   `json:"request_id"`
}

// GlanceObservations defines model for GlanceObservations.
type GlanceObservations = []map[string]interface{}

// GlancePlan defines model for GlancePlan.
type GlancePlan struct {
	OK      bool              `json:"ok"`
	Panels  []string          `json:"panels"`
	Targets GlancePlanTargets `json:"targets"`
}

// GlancePlanTargets defines model for GlancePlanTargets.
type GlancePlanTargets struct {
	Infrastructure []GlanceMachineTarget `json:"infrastructure"`
	Weather        GlanceWeatherTarget   `json:"weather"`
}

// GlanceWeatherTarget defines model for GlanceWeatherTarget.
type GlanceWeatherTarget struct {
	Point string `json:"point"`
}

// Inventory One sweep: each kind read, by kind name.
type Inventory map[string]KindReport

// KindReport defines model for KindReport.
type KindReport struct {
	// Connected False when nothing this controller holds can read the kind; absent means it was read.
	Connected    *bool         `json:"connected,omitempty"`
	Error        string        `json:"error,omitempty"`
	OK           bool          `json:"ok"`
	Records      []any         `json:"records"`
	Refusal      string        `json:"refusal,omitempty"`
	RefusedParts []RefusedPart `json:"refused_parts,omitempty"`
}

// LockedAction An action the registry refuses, and the reason it gives.
type LockedAction struct {
	Action string `json:"action"`
	Kind   string `json:"kind"`
	Reason string `json:"reason"`
}

// Material A stored certificate's material, released only to the controller applying it.
type Material struct {
	Domains    []string `json:"domains"`
	Fullchain  string   `json:"fullchain"`
	PrivateKey string   `json:"private_key"`
}

// Operation A queued or claimed operation, as serialize_operation emits it.
type Operation struct {
	Action             string     `json:"action"`
	AttemptCount       int        `json:"attempt_count"`
	ClaimedBy          string     `json:"claimed_by"`
	CompletedAt        *time.Time `json:"completed_at"`
	CreatedAt          time.Time  `json:"created_at"`
	ID                 string     `json:"id"`
	LeaseExpiresAt     *time.Time `json:"lease_expires_at"`
	Reason             string     `json:"reason"`
	RequestedActor     string     `json:"requested_actor"`
	RequestedInterface string     `json:"requested_interface"`
	Resource           string     `json:"resource"`

	// Result The provider's last result for this operation, as Django stored it.
	Result any    `json:"result"`
	State  string `json:"state"`
}

// Pending The next operation (claim/peek). schema_version and resource accompany an operation whose contract resolved; unresolvable explains one that did not (peek only); verification is the action's declared verification policy, when it has one.
type Pending struct {
	OK            bool       `json:"ok"`
	Operation     *Operation `json:"operation"`
	Resource      Resource   `json:"resource,omitempty"`
	SchemaVersion int        `json:"schema_version,omitempty"`
	Unresolvable  string     `json:"unresolvable,omitempty"`

	// Verification The operation's action's verification policy, when it declares one.
	Verification *Verification `json:"verification,omitempty"`
}

// RefusedPart One declared part of a reading that was refused: which part, why, and on what ("" scope for all of it).
type RefusedPart struct {
	Address       string `json:"address,omitempty"`
	ConnectionRef string `json:"connection_ref"`
	Part          string `json:"part"`
	Reason        string `json:"reason"`
	Refusal       string `json:"refusal"`
	Scope         string `json:"scope"`
}

// Resource defines model for Resource.
type Resource struct {
	Enabled    bool   `json:"enabled"`
	Generation int64  `json:"generation"`
	Key        string `json:"key"`
	Kind       string `json:"kind"`

	// Observed What the provider was last seen holding for this resource.
	Observed map[string]interface{} `json:"observed"`

	// Spec Desired state, resolved for the kind. Each provider decodes it into its own type.
	Spec map[string]interface{} `json:"spec"`
}

// StepFailure Work one pass could not finish; subject is the connection ref it used.
type StepFailure struct {
	Reason  string `json:"reason"`
	Step    string `json:"step"`
	Subject string `json:"subject"`
}

// SweepVerdict defines model for SweepVerdict.
type SweepVerdict struct {
	// AgeSeconds Absent before anything has been swept.
	AgeSeconds      int          `json:"age_seconds,omitempty"`
	Carry           []string     `json:"carry"`
	Due             bool         `json:"due"`
	Forced          []ForcedRead `json:"forced"`
	IntervalSeconds int          `json:"interval_seconds"`
	OK              bool         `json:"ok"`
	OnlyKinds       []string     `json:"only_kinds"`
	Reason          string       `json:"reason"`
}

// Verification How long the controller keeps checking that an applied change is actually served, declared by the action it belongs to.
type Verification struct {
	IntervalSeconds int `json:"interval_seconds"`
	TimeoutSeconds  int `json:"timeout_seconds"`
}

// AnalyticsParams defines parameters for Analytics.
type AnalyticsParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// AnalyticsPlanJSONBody defines parameters for AnalyticsPlan.
type AnalyticsPlanJSONBody = []AnalyticsSiteIdentity

// ClaimParams defines parameters for Claim.
type ClaimParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`

	// LeaseSeconds Lease length, 30 to 3600.
	LeaseSeconds int `form:"lease-seconds,omitempty" json:"lease-seconds,omitempty"`

	// Capability A kind:action the controller can perform.
	Capability []string `form:"capability,omitempty" json:"capability,omitempty"`
}

// ConnectionsJSONBody defines parameters for Connections.
type ConnectionsJSONBody = []ConnectionRecord

// ConnectionsParams defines parameters for Connections.
type ConnectionsParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// ExportParams defines parameters for Export.
type ExportParams struct {
	// Resource Managed resource key.
	Resource string `form:"resource" json:"resource"`
}

// GlanceParams defines parameters for Glance.
type GlanceParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// GlancePlanParams defines parameters for GlancePlan.
type GlancePlanParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// InventoryParams defines parameters for Inventory.
type InventoryParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// MaterialParams defines parameters for Material.
type MaterialParams struct {
	// Resource Managed resource key.
	Resource string `form:"resource" json:"resource"`
}

// PeekParams defines parameters for Peek.
type PeekParams struct {
	// Capability A kind:action the controller can perform.
	Capability []string `form:"capability,omitempty" json:"capability,omitempty"`
}

// ReportParams defines parameters for Report.
type ReportParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`

	// Operation Operation id.
	Operation string `form:"operation" json:"operation"`
}

// ScheduleParams defines parameters for Schedule.
type ScheduleParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// StepsJSONBody defines parameters for Steps.
type StepsJSONBody = []StepFailure

// StepsParams defines parameters for Steps.
type StepsParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// SweepDueParams defines parameters for SweepDue.
type SweepDueParams struct {
	// ControllerID The reporting controller.
	ControllerID string `form:"controller-id" json:"controller-id"`
}

// AnalyticsJSONRequestBody defines body for Analytics for application/json ContentType.
type AnalyticsJSONRequestBody = AnalyticsReadings

// AnalyticsPlanJSONRequestBody defines body for AnalyticsPlan for application/json ContentType.
type AnalyticsPlanJSONRequestBody = AnalyticsPlanJSONBody

// ConnectionsJSONRequestBody defines body for Connections for application/json ContentType.
type ConnectionsJSONRequestBody = ConnectionsJSONBody

// GlanceJSONRequestBody defines body for Glance for application/json ContentType.
type GlanceJSONRequestBody = GlanceObservations

// InventoryJSONRequestBody defines body for Inventory for application/json ContentType.
type InventoryJSONRequestBody = Inventory

// ReportJSONRequestBody defines body for Report for application/json ContentType.
type ReportJSONRequestBody = ControllerReport

// StepsJSONRequestBody defines body for Steps for application/json ContentType.
type StepsJSONRequestBody = StepsJSONBody

// Getter for additional properties for Acknowledgement. Returns the specified
// element and whether it was found
func (a Acknowledgement) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Acknowledgement
func (a *Acknowledgement) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Acknowledgement to handle AdditionalProperties
func (a *Acknowledgement) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.OK)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Acknowledgement to handle AdditionalProperties
func (a Acknowledgement) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["ok"], err = json.Marshal(a.OK)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
