# Generated by Django 5.2.14 on 2026-05-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
