# Generated by Django 6.1.1 on 2026-10-04 21:33

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models

import hq.platform.core.rules


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(
                    django.db.models.lookups.GreaterThan(
                        django.db.models.functions.text.Length(django.db.models.functions.text.Trim("title")), 0
                    )
                ),
                field="title",
                name="calendar_entry_has_a_title",
                violation_error_message="Give the entry a title.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(("ends_on__isnull", True), ("ends_on__gte", models.F("starts_on")), _connector="OR"),
                field="ends_on",
                name="calendar_entry_ends_after_it_starts",
                violation_error_message="It cannot end before it starts.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(("ends_at__isnull", True), ("starts_at__isnull", False), _connector="OR"),
                field="ends_at",
                name="calendar_entry_end_time_has_a_start",
                violation_error_message="An end time needs a start time.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    models.Q(("ends_on__gt", models.F("starts_on")), ("ends_on__isnull", False)),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                field="ends_at",
                name="calendar_entry_end_time_follows_start",
                violation_error_message="It cannot end before it starts.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(("interval__gte", 1), ("interval__lte", 366)),
                field="interval",
                name="calendar_entry_interval_in_range",
                violation_error_message="Repeat every 1 to 366.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(("weekdays", ""), ("repeat", "weekly"), _connector="OR"),
                field="weekdays",
                name="calendar_entry_weekdays_only_weekly",
                violation_error_message="Only a weekly entry names its days.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(
                    ("repeat_until__isnull", True), models.Q(("repeat", ""), _negated=True), _connector="OR"
                ),
                field="repeat_until",
                name="calendar_entry_until_only_repeating",
                violation_error_message="Only a repeating entry has an end.",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=hq.platform.core.rules.Rule(
                condition=models.Q(
                    ("repeat_until__isnull", True), ("repeat_until__gte", models.F("starts_on")), _connector="OR"
                ),
                field="repeat_until",
                name="calendar_entry_until_after_it_starts",
                violation_error_message="It cannot stop repeating before it starts.",
            ),
        ),
    ]
