// Package connectapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package connectapi

// Defines values for FieldPurpose.
const (
	FieldPurposeEmpty    FieldPurpose = ""
	FieldPurposeNOTES    FieldPurpose = "NOTES"
	FieldPurposePASSWORD FieldPurpose = "PASSWORD"
	FieldPurposeUSERNAME FieldPurpose = "USERNAME"
)

// Valid indicates whether the value is a known member of the FieldPurpose enum.
func (e FieldPurpose) Valid() bool {
	switch e {
	case FieldPurposeEmpty:
		return true
	case FieldPurposeNOTES:
		return true
	case FieldPurposePASSWORD:
		return true
	case FieldPurposeUSERNAME:
		return true
	default:
		return false
	}
}

// Defines values for FieldType.
const (
	CONCEALED FieldType = "CONCEALED"
	DATE      FieldType = "DATE"
	EMAIL     FieldType = "EMAIL"
	MENU      FieldType = "MENU"
	MONTHYEAR FieldType = "MONTH_YEAR"
	OTP       FieldType = "OTP"
	STRING    FieldType = "STRING"
	URL       FieldType = "URL"
)

// Valid indicates whether the value is a known member of the FieldType enum.
func (e FieldType) Valid() bool {
	switch e {
	case CONCEALED:
		return true
	case DATE:
		return true
	case EMAIL:
		return true
	case MENU:
		return true
	case MONTHYEAR:
		return true
	case OTP:
		return true
	case STRING:
		return true
	case URL:
		return true
	default:
		return false
	}
}

// Defines values for FullItemCategory.
const (
	FullItemCategoryAPICREDENTIAL        FullItemCategory = "API_CREDENTIAL"
	FullItemCategoryBANKACCOUNT          FullItemCategory = "BANK_ACCOUNT"
	FullItemCategoryCREDITCARD           FullItemCategory = "CREDIT_CARD"
	FullItemCategoryCUSTOM               FullItemCategory = "CUSTOM"
	FullItemCategoryDATABASE             FullItemCategory = "DATABASE"
	FullItemCategoryDOCUMENT             FullItemCategory = "DOCUMENT"
	FullItemCategoryDRIVERLICENSE        FullItemCategory = "DRIVER_LICENSE"
	FullItemCategoryEMAILACCOUNT         FullItemCategory = "EMAIL_ACCOUNT"
	FullItemCategoryIDENTITY             FullItemCategory = "IDENTITY"
	FullItemCategoryLOGIN                FullItemCategory = "LOGIN"
	FullItemCategoryMEDICALRECORD        FullItemCategory = "MEDICAL_RECORD"
	FullItemCategoryMEMBERSHIP           FullItemCategory = "MEMBERSHIP"
	FullItemCategoryOUTDOORLICENSE       FullItemCategory = "OUTDOOR_LICENSE"
	FullItemCategoryPASSPORT             FullItemCategory = "PASSPORT"
	FullItemCategoryPASSWORD             FullItemCategory = "PASSWORD"
	FullItemCategoryREWARDPROGRAM        FullItemCategory = "REWARD_PROGRAM"
	FullItemCategorySECURENOTE           FullItemCategory = "SECURE_NOTE"
	FullItemCategorySERVER               FullItemCategory = "SERVER"
	FullItemCategorySOCIALSECURITYNUMBER FullItemCategory = "SOCIAL_SECURITY_NUMBER"
	FullItemCategorySOFTWARELICENSE      FullItemCategory = "SOFTWARE_LICENSE"
	FullItemCategorySSHKEY               FullItemCategory = "SSH_KEY"
	FullItemCategoryWIRELESSROUTER       FullItemCategory = "WIRELESS_ROUTER"
)

// Valid indicates whether the value is a known member of the FullItemCategory enum.
func (e FullItemCategory) Valid() bool {
	switch e {
	case FullItemCategoryAPICREDENTIAL:
		return true
	case FullItemCategoryBANKACCOUNT:
		return true
	case FullItemCategoryCREDITCARD:
		return true
	case FullItemCategoryCUSTOM:
		return true
	case FullItemCategoryDATABASE:
		return true
	case FullItemCategoryDOCUMENT:
		return true
	case FullItemCategoryDRIVERLICENSE:
		return true
	case FullItemCategoryEMAILACCOUNT:
		return true
	case FullItemCategoryIDENTITY:
		return true
	case FullItemCategoryLOGIN:
		return true
	case FullItemCategoryMEDICALRECORD:
		return true
	case FullItemCategoryMEMBERSHIP:
		return true
	case FullItemCategoryOUTDOORLICENSE:
		return true
	case FullItemCategoryPASSPORT:
		return true
	case FullItemCategoryPASSWORD:
		return true
	case FullItemCategoryREWARDPROGRAM:
		return true
	case FullItemCategorySECURENOTE:
		return true
	case FullItemCategorySERVER:
		return true
	case FullItemCategorySOCIALSECURITYNUMBER:
		return true
	case FullItemCategorySOFTWARELICENSE:
		return true
	case FullItemCategorySSHKEY:
		return true
	case FullItemCategoryWIRELESSROUTER:
		return true
	default:
		return false
	}
}

// Defines values for FullItemState.
const (
	FullItemStateARCHIVED FullItemState = "ARCHIVED"
	FullItemStateDELETED  FullItemState = "DELETED"
)

// Valid indicates whether the value is a known member of the FullItemState enum.
func (e FullItemState) Valid() bool {
	switch e {
	case FullItemStateARCHIVED:
		return true
	case FullItemStateDELETED:
		return true
	default:
		return false
	}
}

// Defines values for GeneratorRecipeCharacterSets.
const (
	DIGITS  GeneratorRecipeCharacterSets = "DIGITS"
	LETTERS GeneratorRecipeCharacterSets = "LETTERS"
	SYMBOLS GeneratorRecipeCharacterSets = "SYMBOLS"
)

// Valid indicates whether the value is a known member of the GeneratorRecipeCharacterSets enum.
func (e GeneratorRecipeCharacterSets) Valid() bool {
	switch e {
	case DIGITS:
		return true
	case LETTERS:
		return true
	case SYMBOLS:
		return true
	default:
		return false
	}
}

// Defines values for ItemCategory.
const (
	ItemCategoryAPICREDENTIAL        ItemCategory = "API_CREDENTIAL"
	ItemCategoryBANKACCOUNT          ItemCategory = "BANK_ACCOUNT"
	ItemCategoryCREDITCARD           ItemCategory = "CREDIT_CARD"
	ItemCategoryCUSTOM               ItemCategory = "CUSTOM"
	ItemCategoryDATABASE             ItemCategory = "DATABASE"
	ItemCategoryDOCUMENT             ItemCategory = "DOCUMENT"
	ItemCategoryDRIVERLICENSE        ItemCategory = "DRIVER_LICENSE"
	ItemCategoryEMAILACCOUNT         ItemCategory = "EMAIL_ACCOUNT"
	ItemCategoryIDENTITY             ItemCategory = "IDENTITY"
	ItemCategoryLOGIN                ItemCategory = "LOGIN"
	ItemCategoryMEDICALRECORD        ItemCategory = "MEDICAL_RECORD"
	ItemCategoryMEMBERSHIP           ItemCategory = "MEMBERSHIP"
	ItemCategoryOUTDOORLICENSE       ItemCategory = "OUTDOOR_LICENSE"
	ItemCategoryPASSPORT             ItemCategory = "PASSPORT"
	ItemCategoryPASSWORD             ItemCategory = "PASSWORD"
	ItemCategoryREWARDPROGRAM        ItemCategory = "REWARD_PROGRAM"
	ItemCategorySECURENOTE           ItemCategory = "SECURE_NOTE"
	ItemCategorySERVER               ItemCategory = "SERVER"
	ItemCategorySOCIALSECURITYNUMBER ItemCategory = "SOCIAL_SECURITY_NUMBER"
	ItemCategorySOFTWARELICENSE      ItemCategory = "SOFTWARE_LICENSE"
	ItemCategorySSHKEY               ItemCategory = "SSH_KEY"
	ItemCategoryWIRELESSROUTER       ItemCategory = "WIRELESS_ROUTER"
)

// Valid indicates whether the value is a known member of the ItemCategory enum.
func (e ItemCategory) Valid() bool {
	switch e {
	case ItemCategoryAPICREDENTIAL:
		return true
	case ItemCategoryBANKACCOUNT:
		return true
	case ItemCategoryCREDITCARD:
		return true
	case ItemCategoryCUSTOM:
		return true
	case ItemCategoryDATABASE:
		return true
	case ItemCategoryDOCUMENT:
		return true
	case ItemCategoryDRIVERLICENSE:
		return true
	case ItemCategoryEMAILACCOUNT:
		return true
	case ItemCategoryIDENTITY:
		return true
	case ItemCategoryLOGIN:
		return true
	case ItemCategoryMEDICALRECORD:
		return true
	case ItemCategoryMEMBERSHIP:
		return true
	case ItemCategoryOUTDOORLICENSE:
		return true
	case ItemCategoryPASSPORT:
		return true
	case ItemCategoryPASSWORD:
		return true
	case ItemCategoryREWARDPROGRAM:
		return true
	case ItemCategorySECURENOTE:
		return true
	case ItemCategorySERVER:
		return true
	case ItemCategorySOCIALSECURITYNUMBER:
		return true
	case ItemCategorySOFTWARELICENSE:
		return true
	case ItemCategorySSHKEY:
		return true
	case ItemCategoryWIRELESSROUTER:
		return true
	default:
		return false
	}
}

// Defines values for ItemState.
const (
	ItemStateARCHIVED ItemState = "ARCHIVED"
	ItemStateDELETED  ItemState = "DELETED"
)

// Valid indicates whether the value is a known member of the ItemState enum.
func (e ItemState) Valid() bool {
	switch e {
	case ItemStateARCHIVED:
		return true
	case ItemStateDELETED:
		return true
	default:
		return false
	}
}

// Defines values for VaultType.
const (
	EVERYONE    VaultType = "EVERYONE"
	PERSONAL    VaultType = "PERSONAL"
	TRANSFER    VaultType = "TRANSFER"
	USERCREATED VaultType = "USER_CREATED"
)

// Valid indicates whether the value is a known member of the VaultType enum.
func (e VaultType) Valid() bool {
	switch e {
	case EVERYONE:
		return true
	case PERSONAL:
		return true
	case TRANSFER:
		return true
	case USERCREATED:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message A message detailing the error
	Message *string `json:"message,omitempty"`

	// Status HTTP Status Code
	Status *int `json:"status,omitempty"`
}

// Field defines model for Field.
type Field struct {
	// Entropy For fields with a purpose of `PASSWORD` this is the entropy of the value
	Entropy *float32 `json:"entropy,omitempty"`

	// Generate If value is not present then a new value should be generated for this field
	Generate *bool   `json:"generate,omitempty"`
	Id       string  `json:"id"`
	Label    *string `json:"label,omitempty"`

	// Purpose Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.
	Purpose *FieldPurpose `json:"purpose,omitempty"`

	// Recipe The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
	Recipe  *GeneratorRecipe `json:"recipe,omitempty"`
	Section *struct {
		Id *string `json:"id,omitempty"`
	} `json:"section,omitempty"`
	Type  FieldType `json:"type"`
	Value *string   `json:"value,omitempty"`
}

// FieldPurpose Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.
type FieldPurpose string

// FieldType defines model for Field.Type.
type FieldType string

// File Example: {"content":"VGhlIGZ1dHVyZSBiZWxvbmdzIHRvIHRoZSBjdXJpb3VzLgo=","content_path":"v1/vaults/ionaiwtdvgclrixbt6ztpqcxnq/items/p7eflcy7f5mk7vg6zrzf5rjjyu/files/6r65pjq33banznomn7q22sj44e/content","id":"6r65pjq33banznomn7q22sj44e","name":"foo.txt","size":35}
type File struct {
	// Content Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`.
	Content *[]byte `json:"content,omitempty"`

	// ContentPath Path of the Connect API that can be used to download the contents of this file.
	ContentPath *string `json:"content_path,omitempty"`

	// Id ID of the file
	Id *string `json:"id,omitempty"`

	// Name Name of the file
	Name *string `json:"name,omitempty"`

	// Section For files that are in a section, this field describes the section.
	Section *struct {
		Id *string `json:"id,omitempty"`
	} `json:"section,omitempty"`

	// Size Size in bytes of the file
	Size *int `json:"size,omitempty"`
}

// FullItem defines model for FullItem.
type FullItem struct {
	Category     FullItemCategory `json:"category"`
	CreatedAt    *string          `json:"createdAt,omitempty"`
	Favorite     *bool            `json:"favorite,omitempty"`
	Fields       *[]Field         `json:"fields,omitempty"`
	Files        *[]File          `json:"files,omitempty"`
	Id           *string          `json:"id,omitempty"`
	LastEditedBy *string          `json:"lastEditedBy,omitempty"`
	Sections     *[]struct {
		Id    *string `json:"id,omitempty"`
		Label *string `json:"label,omitempty"`
	} `json:"sections,omitempty"`
	State     *FullItemState `json:"state,omitempty"`
	Tags      *[]string      `json:"tags,omitempty"`
	Title     *string        `json:"title,omitempty"`
	UpdatedAt *string        `json:"updatedAt,omitempty"`

	// Urls Example: [{"href":"https://example.com","primary":true},{"href":"https://example.org"}]
	Urls *[]struct {
		Href    string  `json:"href"`
		Label   *string `json:"label,omitempty"`
		Primary *bool   `json:"primary,omitempty"`
	} `json:"urls,omitempty"`
	Vault struct {
		Id string `json:"id"`
	} `json:"vault"`
	Version *int `json:"version,omitempty"`
}

// FullItemCategory defines model for FullItem.Category.
type FullItemCategory string

// FullItemState defines model for FullItem.State.
type FullItemState string

// GeneratorRecipe The recipe is used in conjunction with the "generate" property to set the character set used to generate a new secure value
type GeneratorRecipe struct {
	CharacterSets *[]GeneratorRecipeCharacterSets `json:"characterSets,omitempty"`

	// ExcludeCharacters List of all characters that should be excluded from generated passwords.
	//
	// Example: abc1
	ExcludeCharacters *string `json:"excludeCharacters,omitempty"`

	// Length Length of the generated value
	Length *int `json:"length,omitempty"`
}

// GeneratorRecipeCharacterSets defines model for GeneratorRecipe.CharacterSets.
type GeneratorRecipeCharacterSets string

// Item defines model for Item.
type Item struct {
	Category     ItemCategory `json:"category"`
	CreatedAt    *string      `json:"createdAt,omitempty"`
	Favorite     *bool        `json:"favorite,omitempty"`
	Id           *string      `json:"id,omitempty"`
	LastEditedBy *string      `json:"lastEditedBy,omitempty"`
	State        *ItemState   `json:"state,omitempty"`
	Tags         *[]string    `json:"tags,omitempty"`
	Title        *string      `json:"title,omitempty"`
	UpdatedAt    *string      `json:"updatedAt,omitempty"`

	// Urls Example: [{"href":"https://example.com","primary":true},{"href":"https://example.org"}]
	Urls *[]struct {
		Href    string  `json:"href"`
		Label   *string `json:"label,omitempty"`
		Primary *bool   `json:"primary,omitempty"`
	} `json:"urls,omitempty"`
	Vault struct {
		Id string `json:"id"`
	} `json:"vault"`
	Version *int `json:"version,omitempty"`
}

// ItemCategory defines model for Item.Category.
type ItemCategory string

// ItemState defines model for Item.State.
type ItemState string

// ServiceDependency The state of a registered server dependency.
type ServiceDependency struct {
	// Message Human-readable message for explaining the current state.
	Message *string `json:"message,omitempty"`
	Service *string `json:"service,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// Vault defines model for Vault.
type Vault struct {
	// AttributeVersion The vault version
	AttributeVersion *int `json:"attributeVersion,omitempty"`

	// ContentVersion The version of the vault contents
	ContentVersion *int    `json:"contentVersion,omitempty"`
	CreatedAt      *string `json:"createdAt,omitempty"`
	Description    *string `json:"description,omitempty"`
	Id             *string `json:"id,omitempty"`

	// Items Number of active items in the vault
	Items     *int       `json:"items,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Type      *VaultType `json:"type,omitempty"`
	UpdatedAt *string    `json:"updatedAt,omitempty"`
}

// VaultType defines model for Vault.Type.
type VaultType string

// GetVaultsParams defines parameters for GetVaults.
type GetVaultsParams struct {
	// Filter Filter the Vault collection based on Vault name using SCIM eq filter
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetVaultItemsParams defines parameters for GetVaultItems.
type GetVaultItemsParams struct {
	// Filter Filter the Item collection based on Item name using SCIM eq filter
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}
