// Package githubapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package githubapi

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ActionsDefaultWorkflowPermissions.
const (
	ActionsDefaultWorkflowPermissionsRead  ActionsDefaultWorkflowPermissions = "read"
	ActionsDefaultWorkflowPermissionsWrite ActionsDefaultWorkflowPermissions = "write"
)

// Valid indicates whether the value is a known member of the ActionsDefaultWorkflowPermissions enum.
func (e ActionsDefaultWorkflowPermissions) Valid() bool {
	switch e {
	case ActionsDefaultWorkflowPermissionsRead:
		return true
	case ActionsDefaultWorkflowPermissionsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AllowedActions.
const (
	All       AllowedActions = "all"
	LocalOnly AllowedActions = "local_only"
	Selected  AllowedActions = "selected"
)

// Valid indicates whether the value is a known member of the AllowedActions enum.
func (e AllowedActions) Valid() bool {
	switch e {
	case All:
		return true
	case LocalOnly:
		return true
	case Selected:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsActions.
const (
	AppPermissionsActionsRead  AppPermissionsActions = "read"
	AppPermissionsActionsWrite AppPermissionsActions = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsActions enum.
func (e AppPermissionsActions) Valid() bool {
	switch e {
	case AppPermissionsActionsRead:
		return true
	case AppPermissionsActionsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsActionsVariables.
const (
	AppPermissionsActionsVariablesRead  AppPermissionsActionsVariables = "read"
	AppPermissionsActionsVariablesWrite AppPermissionsActionsVariables = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsActionsVariables enum.
func (e AppPermissionsActionsVariables) Valid() bool {
	switch e {
	case AppPermissionsActionsVariablesRead:
		return true
	case AppPermissionsActionsVariablesWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsAdministration.
const (
	AppPermissionsAdministrationRead  AppPermissionsAdministration = "read"
	AppPermissionsAdministrationWrite AppPermissionsAdministration = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsAdministration enum.
func (e AppPermissionsAdministration) Valid() bool {
	switch e {
	case AppPermissionsAdministrationRead:
		return true
	case AppPermissionsAdministrationWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsChecks.
const (
	AppPermissionsChecksRead  AppPermissionsChecks = "read"
	AppPermissionsChecksWrite AppPermissionsChecks = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsChecks enum.
func (e AppPermissionsChecks) Valid() bool {
	switch e {
	case AppPermissionsChecksRead:
		return true
	case AppPermissionsChecksWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsContents.
const (
	AppPermissionsContentsRead  AppPermissionsContents = "read"
	AppPermissionsContentsWrite AppPermissionsContents = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsContents enum.
func (e AppPermissionsContents) Valid() bool {
	switch e {
	case AppPermissionsContentsRead:
		return true
	case AppPermissionsContentsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsDeployments.
const (
	AppPermissionsDeploymentsRead  AppPermissionsDeployments = "read"
	AppPermissionsDeploymentsWrite AppPermissionsDeployments = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsDeployments enum.
func (e AppPermissionsDeployments) Valid() bool {
	switch e {
	case AppPermissionsDeploymentsRead:
		return true
	case AppPermissionsDeploymentsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsMetadata.
const (
	AppPermissionsMetadataRead  AppPermissionsMetadata = "read"
	AppPermissionsMetadataWrite AppPermissionsMetadata = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsMetadata enum.
func (e AppPermissionsMetadata) Valid() bool {
	switch e {
	case AppPermissionsMetadataRead:
		return true
	case AppPermissionsMetadataWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsPackages.
const (
	AppPermissionsPackagesRead  AppPermissionsPackages = "read"
	AppPermissionsPackagesWrite AppPermissionsPackages = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsPackages enum.
func (e AppPermissionsPackages) Valid() bool {
	switch e {
	case AppPermissionsPackagesRead:
		return true
	case AppPermissionsPackagesWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsPullRequests.
const (
	AppPermissionsPullRequestsRead  AppPermissionsPullRequests = "read"
	AppPermissionsPullRequestsWrite AppPermissionsPullRequests = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsPullRequests enum.
func (e AppPermissionsPullRequests) Valid() bool {
	switch e {
	case AppPermissionsPullRequestsRead:
		return true
	case AppPermissionsPullRequestsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsSecretScanningAlerts.
const (
	AppPermissionsSecretScanningAlertsRead  AppPermissionsSecretScanningAlerts = "read"
	AppPermissionsSecretScanningAlertsWrite AppPermissionsSecretScanningAlerts = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsSecretScanningAlerts enum.
func (e AppPermissionsSecretScanningAlerts) Valid() bool {
	switch e {
	case AppPermissionsSecretScanningAlertsRead:
		return true
	case AppPermissionsSecretScanningAlertsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsSecurityEvents.
const (
	AppPermissionsSecurityEventsRead  AppPermissionsSecurityEvents = "read"
	AppPermissionsSecurityEventsWrite AppPermissionsSecurityEvents = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsSecurityEvents enum.
func (e AppPermissionsSecurityEvents) Valid() bool {
	switch e {
	case AppPermissionsSecurityEventsRead:
		return true
	case AppPermissionsSecurityEventsWrite:
		return true
	default:
		return false
	}
}

// Defines values for AppPermissionsVulnerabilityAlerts.
const (
	AppPermissionsVulnerabilityAlertsRead  AppPermissionsVulnerabilityAlerts = "read"
	AppPermissionsVulnerabilityAlertsWrite AppPermissionsVulnerabilityAlerts = "write"
)

// Valid indicates whether the value is a known member of the AppPermissionsVulnerabilityAlerts enum.
func (e AppPermissionsVulnerabilityAlerts) Valid() bool {
	switch e {
	case AppPermissionsVulnerabilityAlertsRead:
		return true
	case AppPermissionsVulnerabilityAlertsWrite:
		return true
	default:
		return false
	}
}

// Defines values for CheckRunConclusion.
const (
	CheckRunConclusionActionRequired CheckRunConclusion = "action_required"
	CheckRunConclusionCancelled      CheckRunConclusion = "cancelled"
	CheckRunConclusionFailure        CheckRunConclusion = "failure"
	CheckRunConclusionNeutral        CheckRunConclusion = "neutral"
	CheckRunConclusionSkipped        CheckRunConclusion = "skipped"
	CheckRunConclusionSuccess        CheckRunConclusion = "success"
	CheckRunConclusionTimedOut       CheckRunConclusion = "timed_out"
)

// Valid indicates whether the value is a known member of the CheckRunConclusion enum.
func (e CheckRunConclusion) Valid() bool {
	switch e {
	case CheckRunConclusionActionRequired:
		return true
	case CheckRunConclusionCancelled:
		return true
	case CheckRunConclusionFailure:
		return true
	case CheckRunConclusionNeutral:
		return true
	case CheckRunConclusionSkipped:
		return true
	case CheckRunConclusionSuccess:
		return true
	case CheckRunConclusionTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for CheckRunStatus.
const (
	CheckRunStatusCompleted  CheckRunStatus = "completed"
	CheckRunStatusInProgress CheckRunStatus = "in_progress"
	CheckRunStatusPending    CheckRunStatus = "pending"
	CheckRunStatusQueued     CheckRunStatus = "queued"
	CheckRunStatusRequested  CheckRunStatus = "requested"
	CheckRunStatusWaiting    CheckRunStatus = "waiting"
)

// Valid indicates whether the value is a known member of the CheckRunStatus enum.
func (e CheckRunStatus) Valid() bool {
	switch e {
	case CheckRunStatusCompleted:
		return true
	case CheckRunStatusInProgress:
		return true
	case CheckRunStatusPending:
		return true
	case CheckRunStatusQueued:
		return true
	case CheckRunStatusRequested:
		return true
	case CheckRunStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for CodeScanningAlertRuleSummarySecuritySeverityLevel.
const (
	CodeScanningAlertRuleSummarySecuritySeverityLevelCritical CodeScanningAlertRuleSummarySecuritySeverityLevel = "critical"
	CodeScanningAlertRuleSummarySecuritySeverityLevelHigh     CodeScanningAlertRuleSummarySecuritySeverityLevel = "high"
	CodeScanningAlertRuleSummarySecuritySeverityLevelLow      CodeScanningAlertRuleSummarySecuritySeverityLevel = "low"
	CodeScanningAlertRuleSummarySecuritySeverityLevelMedium   CodeScanningAlertRuleSummarySecuritySeverityLevel = "medium"
)

// Valid indicates whether the value is a known member of the CodeScanningAlertRuleSummarySecuritySeverityLevel enum.
func (e CodeScanningAlertRuleSummarySecuritySeverityLevel) Valid() bool {
	switch e {
	case CodeScanningAlertRuleSummarySecuritySeverityLevelCritical:
		return true
	case CodeScanningAlertRuleSummarySecuritySeverityLevelHigh:
		return true
	case CodeScanningAlertRuleSummarySecuritySeverityLevelLow:
		return true
	case CodeScanningAlertRuleSummarySecuritySeverityLevelMedium:
		return true
	default:
		return false
	}
}

// Defines values for CodeScanningAlertRuleSummarySeverity.
const (
	CodeScanningAlertRuleSummarySeverityError   CodeScanningAlertRuleSummarySeverity = "error"
	CodeScanningAlertRuleSummarySeverityNone    CodeScanningAlertRuleSummarySeverity = "none"
	CodeScanningAlertRuleSummarySeverityNote    CodeScanningAlertRuleSummarySeverity = "note"
	CodeScanningAlertRuleSummarySeverityWarning CodeScanningAlertRuleSummarySeverity = "warning"
)

// Valid indicates whether the value is a known member of the CodeScanningAlertRuleSummarySeverity enum.
func (e CodeScanningAlertRuleSummarySeverity) Valid() bool {
	switch e {
	case CodeScanningAlertRuleSummarySeverityError:
		return true
	case CodeScanningAlertRuleSummarySeverityNone:
		return true
	case CodeScanningAlertRuleSummarySeverityNote:
		return true
	case CodeScanningAlertRuleSummarySeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for ContentDirectoryType.
const (
	ContentDirectoryTypeDir       ContentDirectoryType = "dir"
	ContentDirectoryTypeFile      ContentDirectoryType = "file"
	ContentDirectoryTypeSubmodule ContentDirectoryType = "submodule"
	ContentDirectoryTypeSymlink   ContentDirectoryType = "symlink"
)

// Valid indicates whether the value is a known member of the ContentDirectoryType enum.
func (e ContentDirectoryType) Valid() bool {
	switch e {
	case ContentDirectoryTypeDir:
		return true
	case ContentDirectoryTypeFile:
		return true
	case ContentDirectoryTypeSubmodule:
		return true
	case ContentDirectoryTypeSymlink:
		return true
	default:
		return false
	}
}

// Defines values for DependabotAlertSecurityAdvisorySeverity.
const (
	DependabotAlertSecurityAdvisorySeverityCritical DependabotAlertSecurityAdvisorySeverity = "critical"
	DependabotAlertSecurityAdvisorySeverityHigh     DependabotAlertSecurityAdvisorySeverity = "high"
	DependabotAlertSecurityAdvisorySeverityLow      DependabotAlertSecurityAdvisorySeverity = "low"
	DependabotAlertSecurityAdvisorySeverityMedium   DependabotAlertSecurityAdvisorySeverity = "medium"
)

// Valid indicates whether the value is a known member of the DependabotAlertSecurityAdvisorySeverity enum.
func (e DependabotAlertSecurityAdvisorySeverity) Valid() bool {
	switch e {
	case DependabotAlertSecurityAdvisorySeverityCritical:
		return true
	case DependabotAlertSecurityAdvisorySeverityHigh:
		return true
	case DependabotAlertSecurityAdvisorySeverityLow:
		return true
	case DependabotAlertSecurityAdvisorySeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentReviewerType.
const (
	DeploymentReviewerTypeTeam DeploymentReviewerType = "Team"
	DeploymentReviewerTypeUser DeploymentReviewerType = "User"
)

// Valid indicates whether the value is a known member of the DeploymentReviewerType enum.
func (e DeploymentReviewerType) Valid() bool {
	switch e {
	case DeploymentReviewerTypeTeam:
		return true
	case DeploymentReviewerTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatusState.
const (
	DeploymentStatusStateError      DeploymentStatusState = "error"
	DeploymentStatusStateFailure    DeploymentStatusState = "failure"
	DeploymentStatusStateInProgress DeploymentStatusState = "in_progress"
	DeploymentStatusStateInactive   DeploymentStatusState = "inactive"
	DeploymentStatusStatePending    DeploymentStatusState = "pending"
	DeploymentStatusStateQueued     DeploymentStatusState = "queued"
	DeploymentStatusStateSuccess    DeploymentStatusState = "success"
)

// Valid indicates whether the value is a known member of the DeploymentStatusState enum.
func (e DeploymentStatusState) Valid() bool {
	switch e {
	case DeploymentStatusStateError:
		return true
	case DeploymentStatusStateFailure:
		return true
	case DeploymentStatusStateInProgress:
		return true
	case DeploymentStatusStateInactive:
		return true
	case DeploymentStatusStatePending:
		return true
	case DeploymentStatusStateQueued:
		return true
	case DeploymentStatusStateSuccess:
		return true
	default:
		return false
	}
}

// Defines values for JobStepsStatus.
const (
	JobStepsStatusCompleted  JobStepsStatus = "completed"
	JobStepsStatusInProgress JobStepsStatus = "in_progress"
	JobStepsStatusQueued     JobStepsStatus = "queued"
)

// Valid indicates whether the value is a known member of the JobStepsStatus enum.
func (e JobStepsStatus) Valid() bool {
	switch e {
	case JobStepsStatusCompleted:
		return true
	case JobStepsStatusInProgress:
		return true
	case JobStepsStatusQueued:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleDetailed0ParametersAllowedMergeMethods.
const (
	RepositoryRuleDetailed0ParametersAllowedMergeMethodsMerge  RepositoryRuleDetailed0ParametersAllowedMergeMethods = "merge"
	RepositoryRuleDetailed0ParametersAllowedMergeMethodsRebase RepositoryRuleDetailed0ParametersAllowedMergeMethods = "rebase"
	RepositoryRuleDetailed0ParametersAllowedMergeMethodsSquash RepositoryRuleDetailed0ParametersAllowedMergeMethods = "squash"
)

// Valid indicates whether the value is a known member of the RepositoryRuleDetailed0ParametersAllowedMergeMethods enum.
func (e RepositoryRuleDetailed0ParametersAllowedMergeMethods) Valid() bool {
	switch e {
	case RepositoryRuleDetailed0ParametersAllowedMergeMethodsMerge:
		return true
	case RepositoryRuleDetailed0ParametersAllowedMergeMethodsRebase:
		return true
	case RepositoryRuleDetailed0ParametersAllowedMergeMethodsSquash:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleDetailed0RulesetSourceType.
const (
	RepositoryRuleDetailed0RulesetSourceTypeOrganization RepositoryRuleDetailed0RulesetSourceType = "Organization"
	RepositoryRuleDetailed0RulesetSourceTypeRepository   RepositoryRuleDetailed0RulesetSourceType = "Repository"
)

// Valid indicates whether the value is a known member of the RepositoryRuleDetailed0RulesetSourceType enum.
func (e RepositoryRuleDetailed0RulesetSourceType) Valid() bool {
	switch e {
	case RepositoryRuleDetailed0RulesetSourceTypeOrganization:
		return true
	case RepositoryRuleDetailed0RulesetSourceTypeRepository:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleDetailed1RulesetSourceType.
const (
	RepositoryRuleDetailed1RulesetSourceTypeOrganization RepositoryRuleDetailed1RulesetSourceType = "Organization"
	RepositoryRuleDetailed1RulesetSourceTypeRepository   RepositoryRuleDetailed1RulesetSourceType = "Repository"
)

// Valid indicates whether the value is a known member of the RepositoryRuleDetailed1RulesetSourceType enum.
func (e RepositoryRuleDetailed1RulesetSourceType) Valid() bool {
	switch e {
	case RepositoryRuleDetailed1RulesetSourceTypeOrganization:
		return true
	case RepositoryRuleDetailed1RulesetSourceTypeRepository:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleParamsActorType.
const (
	RepositoryRuleParamsActorTypeIntegrationInstallation RepositoryRuleParamsActorType = "IntegrationInstallation"
	RepositoryRuleParamsActorTypeRepositoryRole          RepositoryRuleParamsActorType = "RepositoryRole"
	RepositoryRuleParamsActorTypeTeam                    RepositoryRuleParamsActorType = "Team"
	RepositoryRuleParamsActorTypeUser                    RepositoryRuleParamsActorType = "User"
)

// Valid indicates whether the value is a known member of the RepositoryRuleParamsActorType enum.
func (e RepositoryRuleParamsActorType) Valid() bool {
	switch e {
	case RepositoryRuleParamsActorTypeIntegrationInstallation:
		return true
	case RepositoryRuleParamsActorTypeRepositoryRole:
		return true
	case RepositoryRuleParamsActorTypeTeam:
		return true
	case RepositoryRuleParamsActorTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleParamsReviewerType.
const (
	RepositoryRuleParamsReviewerTypeTeam RepositoryRuleParamsReviewerType = "Team"
)

// Valid indicates whether the value is a known member of the RepositoryRuleParamsReviewerType enum.
func (e RepositoryRuleParamsReviewerType) Valid() bool {
	switch e {
	case RepositoryRuleParamsReviewerTypeTeam:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRulePullRequestParametersAllowedMergeMethods.
const (
	RepositoryRulePullRequestParametersAllowedMergeMethodsMerge  RepositoryRulePullRequestParametersAllowedMergeMethods = "merge"
	RepositoryRulePullRequestParametersAllowedMergeMethodsRebase RepositoryRulePullRequestParametersAllowedMergeMethods = "rebase"
	RepositoryRulePullRequestParametersAllowedMergeMethodsSquash RepositoryRulePullRequestParametersAllowedMergeMethods = "squash"
)

// Valid indicates whether the value is a known member of the RepositoryRulePullRequestParametersAllowedMergeMethods enum.
func (e RepositoryRulePullRequestParametersAllowedMergeMethods) Valid() bool {
	switch e {
	case RepositoryRulePullRequestParametersAllowedMergeMethodsMerge:
		return true
	case RepositoryRulePullRequestParametersAllowedMergeMethodsRebase:
		return true
	case RepositoryRulePullRequestParametersAllowedMergeMethodsSquash:
		return true
	default:
		return false
	}
}

// Defines values for RepositoryRuleRulesetInfoRulesetSourceType.
const (
	RepositoryRuleRulesetInfoRulesetSourceTypeOrganization RepositoryRuleRulesetInfoRulesetSourceType = "Organization"
	RepositoryRuleRulesetInfoRulesetSourceTypeRepository   RepositoryRuleRulesetInfoRulesetSourceType = "Repository"
)

// Valid indicates whether the value is a known member of the RepositoryRuleRulesetInfoRulesetSourceType enum.
func (e RepositoryRuleRulesetInfoRulesetSourceType) Valid() bool {
	switch e {
	case RepositoryRuleRulesetInfoRulesetSourceTypeOrganization:
		return true
	case RepositoryRuleRulesetInfoRulesetSourceTypeRepository:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowState.
const (
	WorkflowStateActive             WorkflowState = "active"
	WorkflowStateDeleted            WorkflowState = "deleted"
	WorkflowStateDisabledFork       WorkflowState = "disabled_fork"
	WorkflowStateDisabledInactivity WorkflowState = "disabled_inactivity"
	WorkflowStateDisabledManually   WorkflowState = "disabled_manually"
)

// Valid indicates whether the value is a known member of the WorkflowState enum.
func (e WorkflowState) Valid() bool {
	switch e {
	case WorkflowStateActive:
		return true
	case WorkflowStateDeleted:
		return true
	case WorkflowStateDisabledFork:
		return true
	case WorkflowStateDisabledInactivity:
		return true
	case WorkflowStateDisabledManually:
		return true
	default:
		return false
	}
}

// Defines values for ChecksCreateJSONBodyConclusion.
const (
	ChecksCreateJSONBodyConclusionActionRequired ChecksCreateJSONBodyConclusion = "action_required"
	ChecksCreateJSONBodyConclusionCancelled      ChecksCreateJSONBodyConclusion = "cancelled"
	ChecksCreateJSONBodyConclusionFailure        ChecksCreateJSONBodyConclusion = "failure"
	ChecksCreateJSONBodyConclusionNeutral        ChecksCreateJSONBodyConclusion = "neutral"
	ChecksCreateJSONBodyConclusionSkipped        ChecksCreateJSONBodyConclusion = "skipped"
	ChecksCreateJSONBodyConclusionStale          ChecksCreateJSONBodyConclusion = "stale"
	ChecksCreateJSONBodyConclusionSuccess        ChecksCreateJSONBodyConclusion = "success"
	ChecksCreateJSONBodyConclusionTimedOut       ChecksCreateJSONBodyConclusion = "timed_out"
)

// Valid indicates whether the value is a known member of the ChecksCreateJSONBodyConclusion enum.
func (e ChecksCreateJSONBodyConclusion) Valid() bool {
	switch e {
	case ChecksCreateJSONBodyConclusionActionRequired:
		return true
	case ChecksCreateJSONBodyConclusionCancelled:
		return true
	case ChecksCreateJSONBodyConclusionFailure:
		return true
	case ChecksCreateJSONBodyConclusionNeutral:
		return true
	case ChecksCreateJSONBodyConclusionSkipped:
		return true
	case ChecksCreateJSONBodyConclusionStale:
		return true
	case ChecksCreateJSONBodyConclusionSuccess:
		return true
	case ChecksCreateJSONBodyConclusionTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel.
const (
	ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelFailure ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel = "failure"
	ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelNotice  ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel = "notice"
	ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelWarning ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel = "warning"
)

// Valid indicates whether the value is a known member of the ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel enum.
func (e ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel) Valid() bool {
	switch e {
	case ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelFailure:
		return true
	case ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelNotice:
		return true
	case ChecksCreateJSONBodyOutputAnnotationsAnnotationLevelWarning:
		return true
	default:
		return false
	}
}

// Defines values for ChecksCreateJSONBodyStatus.
const (
	ChecksCreateJSONBodyStatusCompleted  ChecksCreateJSONBodyStatus = "completed"
	ChecksCreateJSONBodyStatusInProgress ChecksCreateJSONBodyStatus = "in_progress"
	ChecksCreateJSONBodyStatusPending    ChecksCreateJSONBodyStatus = "pending"
	ChecksCreateJSONBodyStatusQueued     ChecksCreateJSONBodyStatus = "queued"
	ChecksCreateJSONBodyStatusRequested  ChecksCreateJSONBodyStatus = "requested"
	ChecksCreateJSONBodyStatusWaiting    ChecksCreateJSONBodyStatus = "waiting"
)

// Valid indicates whether the value is a known member of the ChecksCreateJSONBodyStatus enum.
func (e ChecksCreateJSONBodyStatus) Valid() bool {
	switch e {
	case ChecksCreateJSONBodyStatusCompleted:
		return true
	case ChecksCreateJSONBodyStatusInProgress:
		return true
	case ChecksCreateJSONBodyStatusPending:
		return true
	case ChecksCreateJSONBodyStatusQueued:
		return true
	case ChecksCreateJSONBodyStatusRequested:
		return true
	case ChecksCreateJSONBodyStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ChecksUpdateJSONBodyConclusion.
const (
	ChecksUpdateJSONBodyConclusionActionRequired ChecksUpdateJSONBodyConclusion = "action_required"
	ChecksUpdateJSONBodyConclusionCancelled      ChecksUpdateJSONBodyConclusion = "cancelled"
	ChecksUpdateJSONBodyConclusionFailure        ChecksUpdateJSONBodyConclusion = "failure"
	ChecksUpdateJSONBodyConclusionNeutral        ChecksUpdateJSONBodyConclusion = "neutral"
	ChecksUpdateJSONBodyConclusionSkipped        ChecksUpdateJSONBodyConclusion = "skipped"
	ChecksUpdateJSONBodyConclusionStale          ChecksUpdateJSONBodyConclusion = "stale"
	ChecksUpdateJSONBodyConclusionSuccess        ChecksUpdateJSONBodyConclusion = "success"
	ChecksUpdateJSONBodyConclusionTimedOut       ChecksUpdateJSONBodyConclusion = "timed_out"
)

// Valid indicates whether the value is a known member of the ChecksUpdateJSONBodyConclusion enum.
func (e ChecksUpdateJSONBodyConclusion) Valid() bool {
	switch e {
	case ChecksUpdateJSONBodyConclusionActionRequired:
		return true
	case ChecksUpdateJSONBodyConclusionCancelled:
		return true
	case ChecksUpdateJSONBodyConclusionFailure:
		return true
	case ChecksUpdateJSONBodyConclusionNeutral:
		return true
	case ChecksUpdateJSONBodyConclusionSkipped:
		return true
	case ChecksUpdateJSONBodyConclusionStale:
		return true
	case ChecksUpdateJSONBodyConclusionSuccess:
		return true
	case ChecksUpdateJSONBodyConclusionTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel.
const (
	ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelFailure ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel = "failure"
	ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelNotice  ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel = "notice"
	ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelWarning ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel = "warning"
)

// Valid indicates whether the value is a known member of the ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel enum.
func (e ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel) Valid() bool {
	switch e {
	case ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelFailure:
		return true
	case ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelNotice:
		return true
	case ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevelWarning:
		return true
	default:
		return false
	}
}

// Defines values for ChecksUpdateJSONBodyStatus.
const (
	ChecksUpdateJSONBodyStatusCompleted  ChecksUpdateJSONBodyStatus = "completed"
	ChecksUpdateJSONBodyStatusInProgress ChecksUpdateJSONBodyStatus = "in_progress"
	ChecksUpdateJSONBodyStatusPending    ChecksUpdateJSONBodyStatus = "pending"
	ChecksUpdateJSONBodyStatusQueued     ChecksUpdateJSONBodyStatus = "queued"
	ChecksUpdateJSONBodyStatusRequested  ChecksUpdateJSONBodyStatus = "requested"
	ChecksUpdateJSONBodyStatusWaiting    ChecksUpdateJSONBodyStatus = "waiting"
)

// Valid indicates whether the value is a known member of the ChecksUpdateJSONBodyStatus enum.
func (e ChecksUpdateJSONBodyStatus) Valid() bool {
	switch e {
	case ChecksUpdateJSONBodyStatusCompleted:
		return true
	case ChecksUpdateJSONBodyStatusInProgress:
		return true
	case ChecksUpdateJSONBodyStatusPending:
		return true
	case ChecksUpdateJSONBodyStatusQueued:
		return true
	case ChecksUpdateJSONBodyStatusRequested:
		return true
	case ChecksUpdateJSONBodyStatusWaiting:
		return true
	default:
		return false
	}
}

// ActionsCanApprovePullRequestReviews Whether GitHub Actions can approve pull requests. Enabling this can be a security risk.
type ActionsCanApprovePullRequestReviews = bool

// ActionsDefaultWorkflowPermissions The default workflow permissions granted to the GITHUB_TOKEN when running workflows.
type ActionsDefaultWorkflowPermissions string

// ActionsGetDefaultWorkflowPermissions defines model for actions-get-default-workflow-permissions.
type ActionsGetDefaultWorkflowPermissions struct {
	// CanApprovePullRequestReviews Whether GitHub Actions can approve pull requests. Enabling this can be a security risk.
	CanApprovePullRequestReviews ActionsCanApprovePullRequestReviews `json:"can_approve_pull_request_reviews"`

	// DefaultWorkflowPermissions The default workflow permissions granted to the GITHUB_TOKEN when running workflows.
	DefaultWorkflowPermissions ActionsDefaultWorkflowPermissions `json:"default_workflow_permissions"`
}

// ActionsRepositoryPermissions defines model for actions-repository-permissions.
type ActionsRepositoryPermissions struct {
	// AllowedActions The permissions policy that controls the actions and reusable workflows that are allowed to run.
	AllowedActions AllowedActions `json:"allowed_actions,omitempty"`

	// ShaPinningRequired Whether actions must be pinned to a full-length commit SHA.
	ShaPinningRequired ShaPinningRequired `json:"sha_pinning_required,omitempty"`
}

// ActionsVariable defines model for actions-variable.
type ActionsVariable struct {
	// Name The name of the variable.
	//
	// Example: USERNAME
	Name string `json:"name"`
}

// AllowedActions The permissions policy that controls the actions and reusable workflows that are allowed to run.
type AllowedActions string

// AppPermissions The permissions granted to the fine-grained access token.
//
// Example: {"contents":"read","deployments":"write","issues":"read","single_file":"read"}
type AppPermissions struct {
	// Actions The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts.
	Actions AppPermissionsActions `json:"actions,omitempty"`

	// ActionsVariables The level of permission to grant the access token to manage GitHub Actions configuration variables.
	ActionsVariables AppPermissionsActionsVariables `json:"actions_variables,omitempty"`

	// Administration The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation.
	Administration AppPermissionsAdministration `json:"administration,omitempty"`

	// Checks The level of permission to grant the access token for checks on code.
	Checks AppPermissionsChecks `json:"checks,omitempty"`

	// Contents The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges.
	Contents AppPermissionsContents `json:"contents,omitempty"`

	// Deployments The level of permission to grant the access token for deployments and deployment statuses.
	Deployments AppPermissionsDeployments `json:"deployments,omitempty"`

	// Metadata The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata.
	Metadata AppPermissionsMetadata `json:"metadata,omitempty"`

	// Packages The level of permission to grant the access token for packages published to GitHub Packages.
	Packages AppPermissionsPackages `json:"packages,omitempty"`

	// PullRequests The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges.
	PullRequests AppPermissionsPullRequests `json:"pull_requests,omitempty"`

	// SecretScanningAlerts The level of permission to grant the access token to view and manage secret scanning alerts.
	SecretScanningAlerts AppPermissionsSecretScanningAlerts `json:"secret_scanning_alerts,omitempty"`

	// SecurityEvents The level of permission to grant the access token to view and manage security events like code scanning alerts.
	SecurityEvents AppPermissionsSecurityEvents `json:"security_events,omitempty"`

	// VulnerabilityAlerts The level of permission to grant the access token to manage Dependabot alerts.
	VulnerabilityAlerts AppPermissionsVulnerabilityAlerts `json:"vulnerability_alerts,omitempty"`
}

// AppPermissionsActions The level of permission to grant the access token for GitHub Actions workflows, workflow runs, and artifacts.
type AppPermissionsActions string

// AppPermissionsActionsVariables The level of permission to grant the access token to manage GitHub Actions configuration variables.
type AppPermissionsActionsVariables string

// AppPermissionsAdministration The level of permission to grant the access token for repository creation, deletion, settings, teams, and collaborators creation.
type AppPermissionsAdministration string

// AppPermissionsChecks The level of permission to grant the access token for checks on code.
type AppPermissionsChecks string

// AppPermissionsContents The level of permission to grant the access token for repository contents, commits, branches, downloads, releases, and merges.
type AppPermissionsContents string

// AppPermissionsDeployments The level of permission to grant the access token for deployments and deployment statuses.
type AppPermissionsDeployments string

// AppPermissionsMetadata The level of permission to grant the access token to search repositories, list collaborators, and access repository metadata.
type AppPermissionsMetadata string

// AppPermissionsPackages The level of permission to grant the access token for packages published to GitHub Packages.
type AppPermissionsPackages string

// AppPermissionsPullRequests The level of permission to grant the access token for pull requests and related comments, assignees, labels, milestones, and merges.
type AppPermissionsPullRequests string

// AppPermissionsSecretScanningAlerts The level of permission to grant the access token to view and manage secret scanning alerts.
type AppPermissionsSecretScanningAlerts string

// AppPermissionsSecurityEvents The level of permission to grant the access token to view and manage security events like code scanning alerts.
type AppPermissionsSecurityEvents string

// AppPermissionsVulnerabilityAlerts The level of permission to grant the access token to manage Dependabot alerts.
type AppPermissionsVulnerabilityAlerts string

// Artifact An artifact
type Artifact struct {
	// Expired Whether or not the artifact has expired.
	Expired   bool   `json:"expired"`
	ExpiresAt string `json:"expires_at"`

	// Name The name of the artifact.
	//
	// Example: AdventureWorks.Framework
	Name        string `json:"name"`
	WorkflowRun struct {
		// HeadBranch Example: main
		HeadBranch string `json:"head_branch,omitempty"`

		// HeadRepositoryID Example: 42
		HeadRepositoryID int `json:"head_repository_id,omitempty"`

		// HeadSha Example: 009b8a3a9ccbb128af87f9b1c0f4c62e8a304f6d
		HeadSha string `json:"head_sha,omitempty"`

		// ID Example: 10
		ID int `json:"id,omitempty"`

		// RepositoryID Example: 42
		RepositoryID int `json:"repository_id,omitempty"`
	} `json:"workflow_run,omitempty"`
}

// CheckAutomatedSecurityFixes Check Dependabot security updates
type CheckAutomatedSecurityFixes struct {
	// Enabled Whether Dependabot security updates are enabled for the repository.
	//
	// Example: true
	Enabled bool `json:"enabled"`
}

// CheckRun A check performed on the code of a given code change
type CheckRun struct {
	// Conclusion Example: neutral
	Conclusion CheckRunConclusion `json:"conclusion"`

	// ID The id of the check.
	//
	// Example: 21
	ID int `json:"id"`

	// Name The name of the check.
	//
	// Example: test-coverage
	Name string `json:"name"`

	// StartedAt Example: 2018-05-04T01:14:52Z
	StartedAt string `json:"started_at"`

	// Status The phase of the lifecycle that the check is currently in. Statuses of waiting, requested, and pending are reserved for GitHub Actions check runs.
	//
	// Example: queued
	Status CheckRunStatus `json:"status"`
}

// CheckRunConclusion Example: neutral
type CheckRunConclusion string

// CheckRunStatus The phase of the lifecycle that the check is currently in. Statuses of waiting, requested, and pending are reserved for GitHub Actions check runs.
//
// Example: queued
type CheckRunStatus string

// CodeScanningAlertItems defines model for code-scanning-alert-items.
type CodeScanningAlertItems struct {
	Rule CodeScanningAlertRuleSummary `json:"rule"`
}

// CodeScanningAlertRuleSummary defines model for code-scanning-alert-rule-summary.
type CodeScanningAlertRuleSummary struct {
	// SecuritySeverityLevel The security severity of the alert.
	SecuritySeverityLevel CodeScanningAlertRuleSummarySecuritySeverityLevel `json:"security_severity_level,omitempty"`

	// Severity The severity of the alert.
	Severity CodeScanningAlertRuleSummarySeverity `json:"severity,omitempty"`
}

// CodeScanningAlertRuleSummarySecuritySeverityLevel The security severity of the alert.
type CodeScanningAlertRuleSummarySecuritySeverityLevel string

// CodeScanningAlertRuleSummarySeverity The severity of the alert.
type CodeScanningAlertRuleSummarySeverity string

// Collaborator Collaborator
type Collaborator struct {
	// Login Example: octocat
	Login string `json:"login"`

	// RoleName Example: admin
	RoleName string `json:"role_name"`
}

// Commit Commit
type Commit struct {
	Author Commit_Author `json:"author"`
	Commit struct {
		// Author Metaproperties for Git author/committer information.
		Author NullableGitUser `json:"author"`

		// CommentCount Example: 0
		CommentCount int `json:"comment_count"`

		// Committer Metaproperties for Git author/committer information.
		Committer NullableGitUser `json:"committer"`

		// Message Example: Fix all the bugs
		Message string `json:"message"`
		Tree    struct {
			// Sha Example: 827efc6d56897b048c772eb4087f854f46256132
			Sha string `json:"sha"`

			// URL Example: https://api.github.com/repos/octocat/Hello-World/tree/827efc6d56897b048c772eb4087f854f46256132
			URL string `json:"url"`
		} `json:"tree"`

		// URL Example: https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e
		URL          string       `json:"url"`
		Verification Verification `json:"verification,omitempty"`
	} `json:"commit"`

	// HTMLURL Example: https://github.com/octocat/Hello-World/commit/6dcb09b5b57875f334f61aebed695e2e4193db5e
	HTMLURL string `json:"html_url"`

	// Sha Example: 6dcb09b5b57875f334f61aebed695e2e4193db5e
	Sha string `json:"sha"`
}

// Commit_Author defines model for Commit.Author.
type Commit_Author struct {
	union json.RawMessage
}

// ContentDirectory A list of directory items
type ContentDirectory = []struct {
	UnderscoreLinks struct {
		Git  string `json:"git"`
		HTML string `json:"html"`
		Self string `json:"self"`
	} `json:"_links"`
	Content     string               `json:"content,omitempty"`
	DownloadURL string               `json:"download_url"`
	GitURL      string               `json:"git_url"`
	HTMLURL     string               `json:"html_url"`
	Name        string               `json:"name"`
	Path        string               `json:"path"`
	Sha         string               `json:"sha"`
	Size        int                  `json:"size"`
	Type        ContentDirectoryType `json:"type"`
	URL         string               `json:"url"`
}

// ContentDirectoryType defines model for ContentDirectory.Type.
type ContentDirectoryType string

// ContentFile Content File
type ContentFile struct {
	Content string `json:"content"`
}

// DependabotAlert A Dependabot alert.
type DependabotAlert struct {
	// SecurityAdvisory Details for the GitHub Security Advisory.
	SecurityAdvisory DependabotAlertSecurityAdvisory `json:"security_advisory"`
}

// DependabotAlertSecurityAdvisory Details for the GitHub Security Advisory.
type DependabotAlertSecurityAdvisory struct {
	// Severity The severity of the advisory.
	Severity DependabotAlertSecurityAdvisorySeverity `json:"severity"`
}

// DependabotAlertSecurityAdvisorySeverity The severity of the advisory.
type DependabotAlertSecurityAdvisorySeverity string

// DeployKey An SSH key granting access to a single repository.
type DeployKey struct {
	CreatedAt string `json:"created_at"`
	LastUsed  string `json:"last_used,omitempty"`
	ReadOnly  bool   `json:"read_only"`
	Title     string `json:"title"`
}

// Deployment A request for a specific ref(branch,sha,tag) to be deployed
type Deployment struct {
	// CreatedAt Example: 2012-07-20T01:19:13Z
	CreatedAt string `json:"created_at"`

	// Environment Name for the target deployment environment.
	//
	// Example: production
	Environment string `json:"environment"`

	// ID Unique identifier of the deployment
	//
	// Example: 42
	ID int `json:"id"`

	// Sha Example: a84d88e7554fc1fa21bcbc4efae3c782a70d2b9d
	Sha string `json:"sha"`
}

// DeploymentBranchPolicySettings The type of deployment branch policy for this environment. To allow all branches to deploy, set to `null`.
type DeploymentBranchPolicySettings struct {
	// CustomBranchPolicies Whether only branches that match the specified name patterns can deploy to this environment.  If `custom_branch_policies` is `true`, `protected_branches` must be `false`; if `custom_branch_policies` is `false`, `protected_branches` must be `true`.
	CustomBranchPolicies bool `json:"custom_branch_policies"`

	// ProtectedBranches Whether only branches with branch protection rules can deploy to this environment. If `protected_branches` is `true`, `custom_branch_policies` must be `false`; if `protected_branches` is `false`, `custom_branch_policies` must be `true`.
	ProtectedBranches bool `json:"protected_branches"`
}

// DeploymentReviewerType The type of reviewer.
//
// Example: User
type DeploymentReviewerType string

// DeploymentStatus The status of a deployment.
type DeploymentStatus struct {
	// LogURL The URL to associate with this status.
	//
	// Example: https://example.com/deployment/42/output
	LogURL string `json:"log_url,omitempty"`

	// State The state of the status.
	//
	// Example: success
	State DeploymentStatusState `json:"state"`

	// TargetURL Closing down notice: the URL to associate with this status.
	//
	// Example: https://example.com/deployment/42/output
	TargetURL string `json:"target_url"`
}

// DeploymentStatusState The state of the status.
//
// Example: success
type DeploymentStatusState string

// EmptyObject An object without any properties.
type EmptyObject = map[string]interface{}

// Enterprise An enterprise on GitHub.
type Enterprise struct {
	AvatarURL string `json:"avatar_url"`

	// CreatedAt Example: 2019-01-26T19:01:12Z
	CreatedAt string `json:"created_at"`

	// Description A short description of the enterprise.
	Description string `json:"description,omitempty"`

	// HTMLURL Example: https://github.com/enterprises/octo-business
	HTMLURL string `json:"html_url"`

	// ID Unique identifier of the enterprise
	//
	// Example: 42
	ID int `json:"id"`

	// Name The name of the enterprise.
	//
	// Example: Octo Business
	Name string `json:"name"`

	// NodeID Example: MDEwOlJlcG9zaXRvcnkxMjk2MjY5
	NodeID string `json:"node_id"`

	// Slug The slug url identifier for the enterprise.
	//
	// Example: octo-business
	Slug string `json:"slug"`

	// UpdatedAt Example: 2019-01-26T19:14:43Z
	UpdatedAt string `json:"updated_at"`

	// WebsiteURL The enterprise's website URL.
	WebsiteURL string `json:"website_url,omitempty"`
}

// Environment Details of a deployment environment
type Environment struct {
	// DeploymentBranchPolicy The type of deployment branch policy for this environment. To allow all branches to deploy, set to `null`.
	DeploymentBranchPolicy DeploymentBranchPolicySettings `json:"deployment_branch_policy,omitempty"`

	// Name The name of the environment.
	//
	// Example: staging
	Name string `json:"name"`

	// ProtectionRules Built-in deployment protection rules for the environment.
	ProtectionRules []Environment_ProtectionRules_Item `json:"protection_rules,omitempty"`
}

// EnvironmentProtectionRules0 defines model for Environment.ProtectionRules.0.
type EnvironmentProtectionRules0 struct {
	// ID Example: 3515
	ID int `json:"id"`

	// NodeID Example: MDQ6R2F0ZTM1MTU=
	NodeID string `json:"node_id"`

	// Type Example: wait_timer
	Type string `json:"type"`

	// WaitTimer The amount of time to delay a job after the job is initially triggered. The time (in minutes) must be an integer between 0 and 43,200 (30 days).
	//
	// Example: 30
	WaitTimer WaitTimer `json:"wait_timer,omitempty"`
}

// EnvironmentProtectionRules1 defines model for Environment.ProtectionRules.1.
type EnvironmentProtectionRules1 struct {
	// ID Example: 3755
	ID int `json:"id"`

	// NodeID Example: MDQ6R2F0ZTM3NTU=
	NodeID string `json:"node_id"`

	// PreventSelfReview Whether deployments to this environment can be approved by the user who created the deployment.
	//
	// Example: false
	PreventSelfReview bool `json:"prevent_self_review,omitempty"`

	// Reviewers The people or teams that may approve jobs that reference the environment. You can list up to six users or teams as reviewers. The reviewers must have at least read access to the repository. Only one of the required reviewers needs to approve the job for it to proceed.
	Reviewers []struct {
		Reviewer Environment_ProtectionRules_1_Reviewers_Reviewer `json:"reviewer,omitempty"`

		// Type The type of reviewer.
		//
		// Example: User
		Type DeploymentReviewerType `json:"type,omitempty"`
	} `json:"reviewers,omitempty"`

	// Type Example: required_reviewers
	Type string `json:"type"`
}

// Environment_ProtectionRules_1_Reviewers_Reviewer defines model for Environment.ProtectionRules.1.Reviewers.Reviewer.
type Environment_ProtectionRules_1_Reviewers_Reviewer struct {
	union json.RawMessage
}

// EnvironmentProtectionRules2 defines model for Environment.ProtectionRules.2.
type EnvironmentProtectionRules2 struct {
	// ID Example: 3515
	ID int `json:"id"`

	// NodeID Example: MDQ6R2F0ZTM1MTU=
	NodeID string `json:"node_id"`

	// Type Example: branch_policy
	Type string `json:"type"`
}

// Environment_ProtectionRules_Item defines model for environment.protection_rules.Item.
type Environment_ProtectionRules_Item struct {
	union json.RawMessage
}

// FullRepository Full Repository
type FullRepository struct {
	// DefaultBranch Example: master
	DefaultBranch string `json:"default_branch"`

	// HTMLURL Example: https://github.com/octocat/Hello-World
	HTMLURL string `json:"html_url"`
	Private bool   `json:"private"`

	// PushedAt Example: 2011-01-26T19:06:43Z
	PushedAt string `json:"pushed_at"`

	// Visibility The repository visibility: public, private, or internal.
	//
	// Example: public
	Visibility string `json:"visibility,omitempty"`
}

// Installation Installation
type Installation struct {
	Account Installation_Account `json:"account"`

	// ID The ID of the installation.
	//
	// Example: 1
	ID int `json:"id"`
}

// Installation_Account defines model for Installation.Account.
type Installation_Account struct {
	union json.RawMessage
}

// InstallationToken Authentication token for a GitHub App installed on a user or org.
type InstallationToken struct {
	Token string `json:"token"`
}

// Integration GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
type Integration struct {
	// Slug The slug name of the GitHub app
	//
	// Example: probot-owners
	Slug string `json:"slug,omitempty"`
}

// IssueComment Comments provide a way for people to collaborate on an issue.
type IssueComment struct {
	// Body Contents of the issue comment
	//
	// Example: What version of Safari were you using when you observed this bug?
	Body string `json:"body,omitempty"`
}

// Job Information of a job execution in a workflow run
type Job struct {
	// Steps Steps in this job.
	Steps []struct {
		// CompletedAt The time that the job finished, in ISO 8601 format.
		//
		// Example: 2019-08-08T08:00:00-07:00
		CompletedAt string `json:"completed_at,omitempty"`

		// Conclusion The outcome of the job.
		//
		// Example: success
		Conclusion string `json:"conclusion"`

		// Name The name of the job.
		//
		// Example: test-coverage
		Name string `json:"name"`

		// Number Example: 1
		Number int `json:"number"`

		// StartedAt The time that the step started, in ISO 8601 format.
		//
		// Example: 2019-08-08T08:00:00-07:00
		StartedAt string `json:"started_at,omitempty"`

		// Status The phase of the lifecycle that the job is currently in.
		//
		// Example: queued
		Status JobStepsStatus `json:"status"`
	} `json:"steps,omitempty"`
}

// JobStepsStatus The phase of the lifecycle that the job is currently in.
//
// Example: queued
type JobStepsStatus string

// NullableGitUser Metaproperties for Git author/committer information.
type NullableGitUser struct {
	// Date Example: "2007-10-29T02:42:39.000-07:00"
	Date string `json:"date,omitempty"`

	// Name Example: "Chris Wanstrath"
	Name string `json:"name,omitempty"`
}

// NullableSimpleUser A GitHub user.
type NullableSimpleUser struct {
	// Login Example: octocat
	Login string `json:"login"`
}

// PendingDeployment Details of a deployment that is waiting for protection rules to pass
type PendingDeployment struct {
	Environment struct {
		// HTMLURL Example: https://github.com/github/hello-world/deployments/activity_log?environments_filter=staging
		HTMLURL string `json:"html_url,omitempty"`

		// ID The id of the environment.
		//
		// Example: 56780428
		ID int `json:"id,omitempty"`

		// Name The name of the environment.
		//
		// Example: staging
		Name string `json:"name,omitempty"`

		// NodeID Example: MDExOkVudmlyb25tZW50NTY3ODA0Mjg=
		NodeID string `json:"node_id,omitempty"`

		// URL Example: https://api.github.com/repos/github/hello-world/environments/staging
		URL string `json:"url,omitempty"`
	} `json:"environment"`
}

// PullRequestSimple Pull Request Simple
type PullRequestSimple struct {
	// Draft Indicates whether or not the pull request is a draft.
	//
	// Example: false
	Draft bool `json:"draft,omitempty"`
	Head  struct {
		Label string `json:"label"`
		Ref   string `json:"ref"`

		// Repo A repository on GitHub.
		Repo Repository `json:"repo"`
		Sha  string     `json:"sha"`

		// User A GitHub user.
		User NullableSimpleUser `json:"user"`
	} `json:"head"`

	// HTMLURL Example: https://github.com/octocat/Hello-World/pull/1347
	HTMLURL string `json:"html_url"`

	// MergedAt Example: 2011-01-26T19:01:12Z
	MergedAt string `json:"merged_at"`

	// Number Example: 1347
	Number int `json:"number"`

	// Title Example: new-feature
	Title string `json:"title"`

	// UpdatedAt Example: 2011-01-26T19:01:12Z
	UpdatedAt string `json:"updated_at"`

	// User A GitHub user.
	User NullableSimpleUser `json:"user"`
}

// Release A release.
type Release struct {
	HTMLURL     string `json:"html_url"`
	PublishedAt string `json:"published_at"`

	// TagName The name of the tag.
	//
	// Example: v1.0.0
	TagName string `json:"tag_name"`
}

// Repository A repository on GitHub.
type Repository struct {
	// FullName Example: octocat/Hello-World
	FullName string `json:"full_name"`
}

// RepositoryRuleDetailed A repository rule with ruleset details.
type RepositoryRuleDetailed struct {
	union json.RawMessage
}

// RepositoryRuleDetailed0 defines model for RepositoryRuleDetailed.0.
type RepositoryRuleDetailed0 struct {
	Parameters struct {
		// AllowedMergeMethods Array of allowed merge methods. Allowed values include `merge`, `squash`, and `rebase`. At least one option must be enabled.
		AllowedMergeMethods []RepositoryRuleDetailed0ParametersAllowedMergeMethods `json:"allowed_merge_methods,omitempty"`

		// DismissStaleReviewsOnPush New, reviewable commits pushed will dismiss previous pull request review approvals.
		DismissStaleReviewsOnPush bool `json:"dismiss_stale_reviews_on_push"`

		// DismissalRestriction Specify people, teams, or apps allowed to dismiss pull request reviews.
		DismissalRestriction RepositoryRuleParamsDismissalRestriction `json:"dismissal_restriction,omitempty"`

		// RequireCodeOwnerReview Require an approving review in pull requests that modify files that have a designated code owner.
		RequireCodeOwnerReview bool `json:"require_code_owner_review"`

		// RequireLastPushApproval Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
		RequireLastPushApproval bool `json:"require_last_push_approval"`

		// RequiredApprovingReviewCount The number of approving reviews that are required before a pull request can be merged.
		RequiredApprovingReviewCount int `json:"required_approving_review_count"`

		// RequiredReviewThreadResolution All conversations on code must be resolved before a pull request can be merged.
		RequiredReviewThreadResolution bool `json:"required_review_thread_resolution"`

		// RequiredReviewers > [!NOTE]
		// > `required_reviewers` is in beta and subject to change.
		//
		// A collection of reviewers and associated file patterns. Each reviewer has a list of file patterns which determine the files that reviewer is required to review.
		RequiredReviewers []RepositoryRuleParamsRequiredReviewerConfiguration `json:"required_reviewers,omitempty"`
	} `json:"parameters,omitempty"`

	// RulesetID The ID of the ruleset that includes this rule.
	RulesetID int `json:"ruleset_id,omitempty"`

	// RulesetSource The name of the source of the ruleset that includes this rule.
	RulesetSource string `json:"ruleset_source,omitempty"`

	// RulesetSourceType The type of source for the ruleset that includes this rule.
	RulesetSourceType RepositoryRuleDetailed0RulesetSourceType `json:"ruleset_source_type,omitempty"`
}

// RepositoryRuleDetailed0ParametersAllowedMergeMethods defines model for RepositoryRuleDetailed.0.Parameters.AllowedMergeMethods.
type RepositoryRuleDetailed0ParametersAllowedMergeMethods string

// RepositoryRuleDetailed0RulesetSourceType The type of source for the ruleset that includes this rule.
type RepositoryRuleDetailed0RulesetSourceType string

// RepositoryRuleDetailed1 defines model for RepositoryRuleDetailed.1.
type RepositoryRuleDetailed1 struct {
	Parameters struct {
		// DoNotEnforceOnCreate Allow repositories and branches to be created if a check would otherwise prohibit it.
		DoNotEnforceOnCreate bool `json:"do_not_enforce_on_create,omitempty"`

		// RequiredStatusChecks Status checks that are required.
		RequiredStatusChecks []RepositoryRuleParamsStatusCheckConfiguration `json:"required_status_checks"`

		// StrictRequiredStatusChecksPolicy Whether pull requests targeting a matching branch must be tested with the latest code. This setting will not take effect unless at least one status check is enabled.
		StrictRequiredStatusChecksPolicy bool `json:"strict_required_status_checks_policy"`
	} `json:"parameters,omitempty"`

	// RulesetID The ID of the ruleset that includes this rule.
	RulesetID int `json:"ruleset_id,omitempty"`

	// RulesetSource The name of the source of the ruleset that includes this rule.
	RulesetSource string `json:"ruleset_source,omitempty"`

	// RulesetSourceType The type of source for the ruleset that includes this rule.
	RulesetSourceType RepositoryRuleDetailed1RulesetSourceType `json:"ruleset_source_type,omitempty"`
}

// RepositoryRuleDetailed1RulesetSourceType The type of source for the ruleset that includes this rule.
type RepositoryRuleDetailed1RulesetSourceType string

// RepositoryRuleParamsActor An actor allowed to dismiss pull request reviews
type RepositoryRuleParamsActor struct {
	// ID ID of the actor that can dismiss reviews.
	ID int `json:"id"`

	// Type The type of the actor
	Type RepositoryRuleParamsActorType `json:"type"`
}

// RepositoryRuleParamsActorType The type of the actor
type RepositoryRuleParamsActorType string

// RepositoryRuleParamsDismissalRestriction Specify people, teams, or apps allowed to dismiss pull request reviews.
type RepositoryRuleParamsDismissalRestriction struct {
	// AllowedActors Specify people, teams, or apps allowed to dismiss pull request reviews.
	AllowedActors []RepositoryRuleParamsActor `json:"allowed_actors,omitempty"`

	// Enabled Whether to restrict review dismissal to specific actors.
	Enabled bool `json:"enabled"`
}

// RepositoryRuleParamsRequiredReviewerConfiguration A reviewing team, and file patterns describing which files they must approve changes to.
type RepositoryRuleParamsRequiredReviewerConfiguration struct {
	// FilePatterns Array of file patterns. Pull requests which change matching files must be approved by the specified team. File patterns use fnmatch syntax.
	FilePatterns []string `json:"file_patterns"`

	// MinimumApprovals Minimum number of approvals required from the specified team. If set to zero, the team will be added to the pull request but approval is optional.
	MinimumApprovals int `json:"minimum_approvals"`

	// Reviewer A required reviewing team
	Reviewer RepositoryRuleParamsReviewer `json:"reviewer"`
}

// RepositoryRuleParamsReviewer A required reviewing team
type RepositoryRuleParamsReviewer struct {
	// ID ID of the reviewer which must review changes to matching files.
	ID int `json:"id"`

	// Type The type of the reviewer
	Type RepositoryRuleParamsReviewerType `json:"type"`
}

// RepositoryRuleParamsReviewerType The type of the reviewer
type RepositoryRuleParamsReviewerType string

// RepositoryRuleParamsStatusCheckConfiguration Required status check
type RepositoryRuleParamsStatusCheckConfiguration struct {
	// Context The status check context name that must be present on the commit.
	Context string `json:"context"`
}

// RepositoryRulePullRequest Require all commits be made to a non-target branch and submitted via a pull request before they can be merged.
type RepositoryRulePullRequest struct {
	Parameters struct {
		// AllowedMergeMethods Array of allowed merge methods. Allowed values include `merge`, `squash`, and `rebase`. At least one option must be enabled.
		AllowedMergeMethods []RepositoryRulePullRequestParametersAllowedMergeMethods `json:"allowed_merge_methods,omitempty"`

		// DismissStaleReviewsOnPush New, reviewable commits pushed will dismiss previous pull request review approvals.
		DismissStaleReviewsOnPush bool `json:"dismiss_stale_reviews_on_push"`

		// DismissalRestriction Specify people, teams, or apps allowed to dismiss pull request reviews.
		DismissalRestriction RepositoryRuleParamsDismissalRestriction `json:"dismissal_restriction,omitempty"`

		// RequireCodeOwnerReview Require an approving review in pull requests that modify files that have a designated code owner.
		RequireCodeOwnerReview bool `json:"require_code_owner_review"`

		// RequireLastPushApproval Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
		RequireLastPushApproval bool `json:"require_last_push_approval"`

		// RequiredApprovingReviewCount The number of approving reviews that are required before a pull request can be merged.
		RequiredApprovingReviewCount int `json:"required_approving_review_count"`

		// RequiredReviewThreadResolution All conversations on code must be resolved before a pull request can be merged.
		RequiredReviewThreadResolution bool `json:"required_review_thread_resolution"`

		// RequiredReviewers > [!NOTE]
		// > `required_reviewers` is in beta and subject to change.
		//
		// A collection of reviewers and associated file patterns. Each reviewer has a list of file patterns which determine the files that reviewer is required to review.
		RequiredReviewers []RepositoryRuleParamsRequiredReviewerConfiguration `json:"required_reviewers,omitempty"`
	} `json:"parameters,omitempty"`
}

// RepositoryRulePullRequestParametersAllowedMergeMethods defines model for RepositoryRulePullRequest.Parameters.AllowedMergeMethods.
type RepositoryRulePullRequestParametersAllowedMergeMethods string

// RepositoryRuleRequiredStatusChecks Choose which status checks must pass before the ref is updated. When enabled, commits must first be pushed to another ref where the checks pass.
type RepositoryRuleRequiredStatusChecks struct {
	Parameters struct {
		// DoNotEnforceOnCreate Allow repositories and branches to be created if a check would otherwise prohibit it.
		DoNotEnforceOnCreate bool `json:"do_not_enforce_on_create,omitempty"`

		// RequiredStatusChecks Status checks that are required.
		RequiredStatusChecks []RepositoryRuleParamsStatusCheckConfiguration `json:"required_status_checks"`

		// StrictRequiredStatusChecksPolicy Whether pull requests targeting a matching branch must be tested with the latest code. This setting will not take effect unless at least one status check is enabled.
		StrictRequiredStatusChecksPolicy bool `json:"strict_required_status_checks_policy"`
	} `json:"parameters,omitempty"`
}

// RepositoryRuleRulesetInfo User-defined metadata to store domain-specific information limited to 8 keys with scalar values.
type RepositoryRuleRulesetInfo struct {
	// RulesetID The ID of the ruleset that includes this rule.
	RulesetID int `json:"ruleset_id,omitempty"`

	// RulesetSource The name of the source of the ruleset that includes this rule.
	RulesetSource string `json:"ruleset_source,omitempty"`

	// RulesetSourceType The type of source for the ruleset that includes this rule.
	RulesetSourceType RepositoryRuleRulesetInfoRulesetSourceType `json:"ruleset_source_type,omitempty"`
}

// RepositoryRuleRulesetInfoRulesetSourceType The type of source for the ruleset that includes this rule.
type RepositoryRuleRulesetInfoRulesetSourceType string

// Runner A self hosted runner
type Runner struct {
	Busy   bool          `json:"busy"`
	Labels []RunnerLabel `json:"labels"`

	// Name The name of the runner.
	//
	// Example: iMac
	Name string `json:"name"`

	// Status The status of the runner.
	//
	// Example: online
	Status string `json:"status"`
}

// RunnerLabel A label for a self hosted runner
type RunnerLabel struct {
	// Name Name of the label.
	Name string `json:"name"`
}

// SecretScanningAlert defines model for secret-scanning-alert.
type SecretScanningAlert = map[string]interface{}

// ShaPinningRequired Whether actions must be pinned to a full-length commit SHA.
type ShaPinningRequired = bool

// SimpleUser A GitHub user.
type SimpleUser struct {
	// Login Example: octocat
	Login string `json:"login"`
}

// Team Groups of organization members that gives permissions on specified repositories.
type Team struct {
	Name string `json:"name"`
}

// Verification defines model for verification.
type Verification struct {
	Payload    string `json:"payload"`
	Reason     string `json:"reason"`
	Signature  string `json:"signature"`
	Verified   bool   `json:"verified"`
	VerifiedAt string `json:"verified_at"`
}

// WaitTimer The amount of time to delay a job after the job is initially triggered. The time (in minutes) must be an integer between 0 and 43,200 (30 days).
//
// Example: 30
type WaitTimer = int

// Workflow A GitHub Actions workflow
type Workflow struct {
	// ID Example: 5
	ID int `json:"id"`

	// Name Example: CI
	Name string `json:"name"`

	// State Example: active
	State WorkflowState `json:"state"`
}

// WorkflowState Example: active
type WorkflowState string

// WorkflowRun An invocation of a workflow
type WorkflowRun struct {
	// Conclusion Example: neutral
	Conclusion string `json:"conclusion"`
	CreatedAt  string `json:"created_at"`

	// Event Example: push
	Event string `json:"event"`

	// HeadBranch Example: master
	HeadBranch string `json:"head_branch"`

	// HeadSha The SHA of the head commit that points to the version of the workflow being run.
	//
	// Example: 009b8a3a9ccbb128af87f9b1c0f4c62e8a304f6d
	HeadSha string `json:"head_sha"`

	// HTMLURL Example: https://github.com/github/hello-world/suites/4
	HTMLURL string `json:"html_url"`

	// ID The ID of the workflow run.
	//
	// Example: 5
	ID int `json:"id"`

	// Name The name of the workflow run.
	//
	// Example: Build
	Name string `json:"name,omitempty"`

	// Status Example: completed
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`

	// WorkflowID The ID of the parent workflow.
	//
	// Example: 5
	WorkflowID int `json:"workflow_id"`
}

// AppsCreateInstallationAccessTokenJSONBody defines parameters for AppsCreateInstallationAccessToken.
type AppsCreateInstallationAccessTokenJSONBody struct {
	// Permissions The permissions granted to the fine-grained access token.
	//
	// Example: {"contents":"read","deployments":"write","issues":"read","single_file":"read"}
	Permissions AppPermissions `json:"permissions,omitempty"`

	// Repositories List of repository names that the token should have access to
	Repositories []string `json:"repositories,omitempty"`

	// RepositoryIds List of repository IDs that the token should have access to
	//
	// Example: [1]
	RepositoryIds []int `json:"repository_ids,omitempty"`
}

// ChecksCreateJSONBody defines parameters for ChecksCreate.
type ChecksCreateJSONBody struct {
	// Actions Displays a button on GitHub that can be clicked to alert your app to do additional tasks. For example, a code linting app can display a button that automatically fixes detected errors. The button created in this object is displayed after the check run completes. When a user clicks the button, GitHub sends the [`check_run.requested_action` webhook](https://docs.github.com/webhooks/event-payloads/#check_run) to your app. Each action includes a `label`, `identifier` and `description`. A maximum of three actions are accepted. To learn more about check runs and requested actions, see "[Check runs and requested actions](https://docs.github.com/rest/guides/using-the-rest-api-to-interact-with-checks#check-runs-and-requested-actions)."
	Actions []struct {
		// Description A short explanation of what this action would do. The maximum size is 40 characters.
		Description string `json:"description"`

		// Identifier A reference for the action on the integrator's system. The maximum size is 20 characters.
		Identifier string `json:"identifier"`

		// Label The text to be displayed on a button in the web UI. The maximum size is 20 characters.
		Label string `json:"label"`
	} `json:"actions,omitempty"`

	// CompletedAt The time the check completed. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	CompletedAt string `json:"completed_at,omitempty"`

	// Conclusion **Required if you provide `completed_at` or a `status` of `completed`**. The final conclusion of the check.
	// **Note:** Providing `conclusion` will automatically set the `status` parameter to `completed`. You cannot change a check run conclusion to `stale`, only GitHub can set this.
	Conclusion ChecksCreateJSONBodyConclusion `json:"conclusion,omitempty"`

	// DetailsURL The URL of the integrator's site that has the full details of the check. If the integrator does not provide this, then the homepage of the GitHub app is used.
	DetailsURL string `json:"details_url,omitempty"`

	// ExternalID A reference for the run on the integrator's system.
	ExternalID string `json:"external_id,omitempty"`

	// HeadSha The SHA of the commit.
	HeadSha string `json:"head_sha"`

	// Name The name of the check. For example, "code-coverage".
	Name string `json:"name"`

	// Output Check runs can accept a variety of data in the `output` object, including a `title` and `summary` and can optionally provide descriptive details about the run.
	Output struct {
		// Annotations Adds information from your analysis to specific lines of code. Annotations are visible on GitHub in the **Checks** and **Files changed** tab of the pull request. The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the [Update a check run](https://docs.github.com/rest/checks/runs#update-a-check-run) endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. GitHub Actions are limited to 10 warning annotations and 10 error annotations per step. For details about how you can view annotations on GitHub, see "[About status checks](https://docs.github.com/articles/about-status-checks#checks)".
		Annotations []struct {
			// AnnotationLevel The level of the annotation.
			AnnotationLevel ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel `json:"annotation_level"`

			// EndColumn The end column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values.
			EndColumn int `json:"end_column,omitempty"`

			// EndLine The end line of the annotation.
			EndLine int `json:"end_line"`

			// Message A short description of the feedback for these lines of code. The maximum size is 64 KB.
			Message string `json:"message"`

			// Path The path of the file to add an annotation to. For example, `assets/css/main.css`.
			Path string `json:"path"`

			// RawDetails Details about this annotation. The maximum size is 64 KB.
			RawDetails string `json:"raw_details,omitempty"`

			// StartColumn The start column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values. Column numbers start at 1.
			StartColumn int `json:"start_column,omitempty"`

			// StartLine The start line of the annotation. Line numbers start at 1.
			StartLine int `json:"start_line"`

			// Title The title that represents the annotation. The maximum size is 255 characters.
			Title string `json:"title,omitempty"`
		} `json:"annotations,omitempty"`

		// Images Adds images to the output displayed in the GitHub pull request UI.
		Images []struct {
			// Alt The alternative text for the image.
			Alt string `json:"alt"`

			// Caption A short image description.
			Caption string `json:"caption,omitempty"`

			// ImageURL The full URL of the image.
			ImageURL string `json:"image_url"`
		} `json:"images,omitempty"`

		// Summary The summary of the check run. This parameter supports Markdown. **Maximum length**: 65535 characters.
		Summary string `json:"summary"`

		// Text The details of the check run. This parameter supports Markdown. **Maximum length**: 65535 characters.
		Text string `json:"text,omitempty"`

		// Title The title of the check run.
		Title string `json:"title"`
	} `json:"output,omitempty"`

	// StartedAt The time that the check run began. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	StartedAt string `json:"started_at,omitempty"`

	// Status The current status of the check run. Only GitHub Actions can set a status of `waiting`, `pending`, or `requested`.
	Status ChecksCreateJSONBodyStatus `json:"status,omitempty"`
}

// ChecksCreateJSONBodyConclusion defines parameters for ChecksCreate.
type ChecksCreateJSONBodyConclusion string

// ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel defines parameters for ChecksCreate.
type ChecksCreateJSONBodyOutputAnnotationsAnnotationLevel string

// ChecksCreateJSONBodyStatus defines parameters for ChecksCreate.
type ChecksCreateJSONBodyStatus string

// ChecksUpdateJSONBody defines parameters for ChecksUpdate.
type ChecksUpdateJSONBody struct {
	// Actions Possible further actions the integrator can perform, which a user may trigger. Each action includes a `label`, `identifier` and `description`. A maximum of three actions are accepted. To learn more about check runs and requested actions, see "[Check runs and requested actions](https://docs.github.com/rest/guides/using-the-rest-api-to-interact-with-checks#check-runs-and-requested-actions)."
	Actions []struct {
		// Description A short explanation of what this action would do. The maximum size is 40 characters.
		Description string `json:"description"`

		// Identifier A reference for the action on the integrator's system. The maximum size is 20 characters.
		Identifier string `json:"identifier"`

		// Label The text to be displayed on a button in the web UI. The maximum size is 20 characters.
		Label string `json:"label"`
	} `json:"actions,omitempty"`

	// CompletedAt The time the check completed. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	CompletedAt string `json:"completed_at,omitempty"`

	// Conclusion **Required if you provide `completed_at` or a `status` of `completed`**. The final conclusion of the check.
	// **Note:** Providing `conclusion` will automatically set the `status` parameter to `completed`. You cannot change a check run conclusion to `stale`, only GitHub can set this.
	Conclusion ChecksUpdateJSONBodyConclusion `json:"conclusion,omitempty"`

	// DetailsURL The URL of the integrator's site that has the full details of the check.
	DetailsURL string `json:"details_url,omitempty"`

	// ExternalID A reference for the run on the integrator's system.
	ExternalID string `json:"external_id,omitempty"`

	// Name The name of the check. For example, "code-coverage".
	Name string `json:"name,omitempty"`

	// Output Check runs can accept a variety of data in the `output` object, including a `title` and `summary` and can optionally provide descriptive details about the run.
	Output struct {
		// Annotations Adds information from your analysis to specific lines of code. Annotations are visible in GitHub's pull request UI. Annotations are visible in GitHub's pull request UI. The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the [Update a check run](https://docs.github.com/rest/checks/runs#update-a-check-run) endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. GitHub Actions are limited to 10 warning annotations and 10 error annotations per step. For details about annotations in the UI, see "[About status checks](https://docs.github.com/articles/about-status-checks#checks)".
		Annotations []struct {
			// AnnotationLevel The level of the annotation.
			AnnotationLevel ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel `json:"annotation_level"`

			// EndColumn The end column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values.
			EndColumn int `json:"end_column,omitempty"`

			// EndLine The end line of the annotation.
			EndLine int `json:"end_line"`

			// Message A short description of the feedback for these lines of code. The maximum size is 64 KB.
			Message string `json:"message"`

			// Path The path of the file to add an annotation to. For example, `assets/css/main.css`.
			Path string `json:"path"`

			// RawDetails Details about this annotation. The maximum size is 64 KB.
			RawDetails string `json:"raw_details,omitempty"`

			// StartColumn The start column of the annotation. Annotations only support `start_column` and `end_column` on the same line. Omit this parameter if `start_line` and `end_line` have different values. Column numbers start at 1.
			StartColumn int `json:"start_column,omitempty"`

			// StartLine The start line of the annotation. Line numbers start at 1.
			StartLine int `json:"start_line"`

			// Title The title that represents the annotation. The maximum size is 255 characters.
			Title string `json:"title,omitempty"`
		} `json:"annotations,omitempty"`

		// Images Adds images to the output displayed in the GitHub pull request UI.
		Images []struct {
			// Alt The alternative text for the image.
			Alt string `json:"alt"`

			// Caption A short image description.
			Caption string `json:"caption,omitempty"`

			// ImageURL The full URL of the image.
			ImageURL string `json:"image_url"`
		} `json:"images,omitempty"`

		// Summary Can contain Markdown.
		Summary string `json:"summary"`

		// Text Can contain Markdown.
		Text string `json:"text,omitempty"`

		// Title **Required**.
		Title string `json:"title,omitempty"`
	} `json:"output,omitempty"`

	// StartedAt This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	StartedAt string `json:"started_at,omitempty"`

	// Status The current status of the check run. Only GitHub Actions can set a status of `waiting`, `pending`, or `requested`.
	Status ChecksUpdateJSONBodyStatus `json:"status,omitempty"`
}

// ChecksUpdateJSONBodyConclusion defines parameters for ChecksUpdate.
type ChecksUpdateJSONBodyConclusion string

// ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel defines parameters for ChecksUpdate.
type ChecksUpdateJSONBodyOutputAnnotationsAnnotationLevel string

// ChecksUpdateJSONBodyStatus defines parameters for ChecksUpdate.
type ChecksUpdateJSONBodyStatus string

// IssuesCreateCommentJSONBody defines parameters for IssuesCreateComment.
type IssuesCreateCommentJSONBody struct {
	// Body The contents of the comment.
	Body string `json:"body"`
}

// AppsCreateInstallationAccessTokenJSONRequestBody defines body for AppsCreateInstallationAccessToken for application/json ContentType.
type AppsCreateInstallationAccessTokenJSONRequestBody AppsCreateInstallationAccessTokenJSONBody

// ChecksCreateJSONRequestBody defines body for ChecksCreate for application/json ContentType.
type ChecksCreateJSONRequestBody ChecksCreateJSONBody

// ChecksUpdateJSONRequestBody defines body for ChecksUpdate for application/json ContentType.
type ChecksUpdateJSONRequestBody ChecksUpdateJSONBody

// IssuesCreateCommentJSONRequestBody defines body for IssuesCreateComment for application/json ContentType.
type IssuesCreateCommentJSONRequestBody IssuesCreateCommentJSONBody

// AsSimpleUser returns the union data inside the Commit_Author as a SimpleUser
func (t Commit_Author) AsSimpleUser() (SimpleUser, error) {
	var body SimpleUser
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleUser overwrites any union data inside the Commit_Author as the provided SimpleUser
func (t *Commit_Author) FromSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleUser performs a merge with any union data inside the Commit_Author, using the provided SimpleUser
func (t *Commit_Author) MergeSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmptyObject returns the union data inside the Commit_Author as a EmptyObject
func (t Commit_Author) AsEmptyObject() (EmptyObject, error) {
	var body EmptyObject
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmptyObject overwrites any union data inside the Commit_Author as the provided EmptyObject
func (t *Commit_Author) FromEmptyObject(v EmptyObject) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmptyObject performs a merge with any union data inside the Commit_Author, using the provided EmptyObject
func (t *Commit_Author) MergeEmptyObject(v EmptyObject) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Commit_Author) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Commit_Author) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSimpleUser returns the union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer as a SimpleUser
func (t Environment_ProtectionRules_1_Reviewers_Reviewer) AsSimpleUser() (SimpleUser, error) {
	var body SimpleUser
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleUser overwrites any union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer as the provided SimpleUser
func (t *Environment_ProtectionRules_1_Reviewers_Reviewer) FromSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleUser performs a merge with any union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer, using the provided SimpleUser
func (t *Environment_ProtectionRules_1_Reviewers_Reviewer) MergeSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTeam returns the union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer as a Team
func (t Environment_ProtectionRules_1_Reviewers_Reviewer) AsTeam() (Team, error) {
	var body Team
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTeam overwrites any union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer as the provided Team
func (t *Environment_ProtectionRules_1_Reviewers_Reviewer) FromTeam(v Team) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTeam performs a merge with any union data inside the Environment_ProtectionRules_1_Reviewers_Reviewer, using the provided Team
func (t *Environment_ProtectionRules_1_Reviewers_Reviewer) MergeTeam(v Team) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Environment_ProtectionRules_1_Reviewers_Reviewer) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Environment_ProtectionRules_1_Reviewers_Reviewer) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEnvironmentProtectionRules0 returns the union data inside the Environment_ProtectionRules_Item as a EnvironmentProtectionRules0
func (t Environment_ProtectionRules_Item) AsEnvironmentProtectionRules0() (EnvironmentProtectionRules0, error) {
	var body EnvironmentProtectionRules0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvironmentProtectionRules0 overwrites any union data inside the Environment_ProtectionRules_Item as the provided EnvironmentProtectionRules0
func (t *Environment_ProtectionRules_Item) FromEnvironmentProtectionRules0(v EnvironmentProtectionRules0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnvironmentProtectionRules0 performs a merge with any union data inside the Environment_ProtectionRules_Item, using the provided EnvironmentProtectionRules0
func (t *Environment_ProtectionRules_Item) MergeEnvironmentProtectionRules0(v EnvironmentProtectionRules0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnvironmentProtectionRules1 returns the union data inside the Environment_ProtectionRules_Item as a EnvironmentProtectionRules1
func (t Environment_ProtectionRules_Item) AsEnvironmentProtectionRules1() (EnvironmentProtectionRules1, error) {
	var body EnvironmentProtectionRules1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvironmentProtectionRules1 overwrites any union data inside the Environment_ProtectionRules_Item as the provided EnvironmentProtectionRules1
func (t *Environment_ProtectionRules_Item) FromEnvironmentProtectionRules1(v EnvironmentProtectionRules1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnvironmentProtectionRules1 performs a merge with any union data inside the Environment_ProtectionRules_Item, using the provided EnvironmentProtectionRules1
func (t *Environment_ProtectionRules_Item) MergeEnvironmentProtectionRules1(v EnvironmentProtectionRules1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnvironmentProtectionRules2 returns the union data inside the Environment_ProtectionRules_Item as a EnvironmentProtectionRules2
func (t Environment_ProtectionRules_Item) AsEnvironmentProtectionRules2() (EnvironmentProtectionRules2, error) {
	var body EnvironmentProtectionRules2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnvironmentProtectionRules2 overwrites any union data inside the Environment_ProtectionRules_Item as the provided EnvironmentProtectionRules2
func (t *Environment_ProtectionRules_Item) FromEnvironmentProtectionRules2(v EnvironmentProtectionRules2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnvironmentProtectionRules2 performs a merge with any union data inside the Environment_ProtectionRules_Item, using the provided EnvironmentProtectionRules2
func (t *Environment_ProtectionRules_Item) MergeEnvironmentProtectionRules2(v EnvironmentProtectionRules2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Environment_ProtectionRules_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Environment_ProtectionRules_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSimpleUser returns the union data inside the Installation_Account as a SimpleUser
func (t Installation_Account) AsSimpleUser() (SimpleUser, error) {
	var body SimpleUser
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSimpleUser overwrites any union data inside the Installation_Account as the provided SimpleUser
func (t *Installation_Account) FromSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSimpleUser performs a merge with any union data inside the Installation_Account, using the provided SimpleUser
func (t *Installation_Account) MergeSimpleUser(v SimpleUser) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEnterprise returns the union data inside the Installation_Account as a Enterprise
func (t Installation_Account) AsEnterprise() (Enterprise, error) {
	var body Enterprise
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEnterprise overwrites any union data inside the Installation_Account as the provided Enterprise
func (t *Installation_Account) FromEnterprise(v Enterprise) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEnterprise performs a merge with any union data inside the Installation_Account, using the provided Enterprise
func (t *Installation_Account) MergeEnterprise(v Enterprise) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Installation_Account) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Installation_Account) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRepositoryRuleDetailed0 returns the union data inside the RepositoryRuleDetailed as a RepositoryRuleDetailed0
func (t RepositoryRuleDetailed) AsRepositoryRuleDetailed0() (RepositoryRuleDetailed0, error) {
	var body RepositoryRuleDetailed0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRepositoryRuleDetailed0 overwrites any union data inside the RepositoryRuleDetailed as the provided RepositoryRuleDetailed0
func (t *RepositoryRuleDetailed) FromRepositoryRuleDetailed0(v RepositoryRuleDetailed0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRepositoryRuleDetailed0 performs a merge with any union data inside the RepositoryRuleDetailed, using the provided RepositoryRuleDetailed0
func (t *RepositoryRuleDetailed) MergeRepositoryRuleDetailed0(v RepositoryRuleDetailed0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRepositoryRuleDetailed1 returns the union data inside the RepositoryRuleDetailed as a RepositoryRuleDetailed1
func (t RepositoryRuleDetailed) AsRepositoryRuleDetailed1() (RepositoryRuleDetailed1, error) {
	var body RepositoryRuleDetailed1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRepositoryRuleDetailed1 overwrites any union data inside the RepositoryRuleDetailed as the provided RepositoryRuleDetailed1
func (t *RepositoryRuleDetailed) FromRepositoryRuleDetailed1(v RepositoryRuleDetailed1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRepositoryRuleDetailed1 performs a merge with any union data inside the RepositoryRuleDetailed, using the provided RepositoryRuleDetailed1
func (t *RepositoryRuleDetailed) MergeRepositoryRuleDetailed1(v RepositoryRuleDetailed1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RepositoryRuleDetailed) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RepositoryRuleDetailed) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
